---
title: "Figure2"
output: html_document
date: "2023-08-01"
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r env}
.libPaths("/stornext/Bioinf/data/lab_brain_cancer/users/t_lu/R/x86_64-pc-linux-gnu-library/4.2")
library(ggplot2)
library(ggpattern)
library(readxl)
library(RRHO2)
library(dplyr)
library(RaMP)
library(magick)
library(rsvg)
library(viridis)
library(ComplexUpset)
library(Cairo)
library(MASS) 
library(reshape2)
library(ggnewscale)
library(magrittr)
library(seriation)
library(cowplot)
library(png)
library(naturalsort)
# Set ramp connection
pkg.globals <- setConnectionToRaMP(
  dbname = "ramp", username = "root", conpass = "ADMIN",
  host = "localhost",socket = "~/mysql.sock")
```


```{r figure2A}
data = readRDS(".../potential_list_long_small_molecules.RDS")

matrix_polarity = paste0(data$matrix, data$polarity)
#
if(length(grep(colnames(data), pattern = "matrix_polarity")) == 0){
  data = cbind(data, matrix_polarity)
}

# num stores the number of unique detected small molecules, num_mz, number of unique m/z s
num = c()
num_mz = c()
num_backgroundmz = c()
#
peaks_file = naturalsort(list.files("~/small_molecule_processed_data",
                        pattern = "Tissue1_T_peaksum.RData"))

for(i in peaks_file){
  load(paste0(i))
  num_backgroundmz = c(num_backgroundmz, nrow(peaksum_b_df))
  num_mz =c(num_mz, nrow(peaksum_df))
}
names(num_backgroundmz) = c("9AA Sublimation-",
                            "9AA Sublimation+",
                            "9AA Sublimation(2step)-",
                            "9AA Sublimation(2step)+",
                            "DHB Sublimation+" ,
                            "DHB Sublimation-",
                            "CHCA sublimation (2step)+",
                            "CHCA sublimation (2step)-",
                            "CHCA sublimation+",
                            "CHCA sublimation-")
#
for(i in 1:length(unique(matrix_polarity))){
  #num_mz[i] = length(unique(data[which(data$matrix_polarity == unique(matrix_polarity)[i] & data$Tissue == "Tissue1" ),]$exp_mz))
  num[i] = length(unique(data[which(data$matrix_polarity == unique(matrix_polarity)[i]& data$Tissue == "Tissue1"),]$chemical_formula))
}
# barplot = store of the data
barplot = data.frame(cbind(c(num,num_mz),
                     mp = rep(unique(matrix_polarity), times = 2)),
                     label = c(rep("Potential chemcial formulas matched", times = length(num)),
                               rep("Experimental m/z", times = length(num)))
                               )

b = ggplot(data = barplot, aes(x = factor(mp, level = c("9AA Sublimation-",
                                                        "9AA Sublimation(2step)-",
                                                        "9AA Sublimation+",
                                                        "9AA Sublimation(2step)+",
                                                        "CHCA sublimation-",
                                                        "CHCA sublimation (2step)-",
                                                        "CHCA sublimation+",
                                                        "CHCA sublimation (2step)+",
                                                        "DHB Sublimation-",
                                                        "DHB Sublimation+")),y = as.integer(V1),fill = mp,pattern = label))+
  geom_bar_pattern(position = "dodge",
                   stat = "identity",
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6)+
  scale_fill_manual(values = c("9AA Sublimation-"="#007AB6",
                                   "9AA Sublimation+" = "#ABC7E6",
                                   "9AA Sublimation(2step)-"="#413975",
                                   "9AA Sublimation(2step)+"= "#9068AC",
                                   "DHB Sublimation+"="#FDB772",
                                   "DHB Sublimation-"="#F77800",
                                   "CHCA sublimation (2step)+"="#5AC096",
                                   "CHCA sublimation (2step)-"= "#2FA143",
                                   "CHCA sublimation+"="#C3A128",
                                   "CHCA sublimation-"="#916729"), guide = "none")+
 # scale_fill_manual(values = rep(c("#007AB6",
 #                                              "#ABC7E6",
 #                                              "#5AC096",
 #                                              "#2FA143"),each = 1), guide = "none")+
  scale_pattern_manual(values = c( `Experimental m/z` = "stripe", 
                                   `Potential chemcial formulas matched` = "none"))+
  labs(x = "Matrix/Polarity combinations", y = "Number of Detected Features", pattern = "Type of Feature") + 
  guides(pattern = guide_legend(override.aes = list(fill = "white")))+
  scale_x_discrete(guide = guide_axis(n.dodge = 1,
                                      angle = 45))+
  theme_bw()+ theme(axis.text.x = element_text(size = 7,
                                               colour =c("9AA Sublimation-"="#007AB6",
                                                         "9AA Sublimation+" = "#ABC7E6",
                                                         "9AA Sublimation(2step)-"="#413975",
                                                         "9AA Sublimation(2step)+"= "#9068AC",
                                                         "DHB Sublimation-"="#F77800",
                                                         "DHB Sublimation+"="#FDB772",
                                                         "CHCA sublimation (2step)-"= "#2FA143",
                                                         "CHCA sublimation (2step)+"="#5AC096",
                                                         "CHCA sublimation-"="#916729",
                                                         "CHCA sublimation+"="#C3A128"
                                                         )),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())  
# Save image 
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(filename = "Figure2A.svg",
       plot = b,
       width=6*1.681, height=6)
```


```{r figure2b}
#########
library(dplyr)
source_directory = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230516_bulk_metabolomics"
lipid = "/Lipids_LCMS"
polar = "/Polar_LCMS"
# Set working directory
setwd(source_directory)
# Get file names
lipidomics = data.frame(t(read_xlsx(path = paste0(source_directory,lipid,"/",
                                     list.files(paste0(source_directory,lipid),
                                                pattern = "MA-SB-606_Lipidomics.xlsx"))))) 
lipidomics =lipidomics%>% `colnames<-`(paste0(lipidomics[1,],lipidomics[2,]))%>% dplyr::slice(-c(1,2))
#######

polar_molecule = data.frame(t(read_xlsx(path = paste0(source_directory,polar,"/",
                                   list.files(paste0(source_directory,polar),
                                              pattern = "xlsx"))[2]))) 
polar_molecule = polar_molecule%>% dplyr::select(-c(X3,X10)) %>%`colnames<-`(polar_molecule[1,-c(3,10)])%>% dplyr::slice(-c(1))
#####
lcmsdata = list(lipid = lipidomics,
                sm =polar_molecule)
#
ims_sm_i = readRDS("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/221222_optimization/data/output/potential_list_long_2023-02-10.RDS")

lcms_sm_hmdb = sub(".*_", "", rownames(lcmsdata[["sm"]]))
lcms_sm = polar_molecule %>% `rownames<-`(lcms_sm_hmdb)
lcms_sm[which(row.names(lcms_sm) == "HMDB0000043"), 1] = 3710 + 7350

####################################################################
matrix_polarity = paste0(ims_sm_i$matrix, ims_sm_i$polarity)
#
if (length(grep(colnames(ims_sm_i), pattern = "matrix_polarity")) == 0) {
  ims_sm_i = cbind(ims_sm_i, matrix_polarity)
}
ims_sm = ims_sm_i#[which(ims_sm_i$Tissue == "Tissue1"),]

### Create a df to store the information of the overlapped metabolites
comparason_table = data.frame()
image = list()
all_matched = list()
###########
setwd(
  "/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/small_molecules/Comparason_with_lcms"
)
for (i in unique(matrix_polarity)) {
  ims_temp = ims_sm[which(ims_sm$matrix_polarity == i),]
  ims_matched = ims_temp[which(ims_temp$accession %in% lcms_sm_hmdb),]
  
  ############################
  temp_acession =  ims_matched$accession
  ############################
  ims_matched = ims_matched[!duplicated(ims_matched$accession),]
  ims_rrho = data.frame(cbind(HMDB = ims_matched$accession, diff_ims = ims_matched$diff_mean))
  # Lcms data
  lcms_temp = lcms_sm[which(rownames(lcms_sm) %in% unique(ims_temp$accession)),]
  #remove background
  tumour_intensity = as.numeric(lcms_temp[, 2]) - as.numeric(lcms_temp[, ncol(lcms_temp)])
  normal_intensity = as.numeric(lcms_temp[, 1]) - as.numeric(lcms_temp[, ncol(lcms_temp)])
  
  normal_intensity =normal_intensity*sum(tumour_intensity)/sum(normal_intensity)
  #
  lcms_fc = log1p(as.numeric(tumour_intensity)) - log1p(as.numeric(normal_intensity))
  lcms_rrho = data.frame(cbind(HMDB = rownames(lcms_temp), diff_lcms =  lcms_fc))
  
  all_matched[[i]] = merge(ims_rrho, lcms_rrho, by = c("HMDB"))
  # mean_dm = log1p(mean(exp(ims_temp[which(ims_temp$accession==temp_acession),]$mean_c)-1)/mean(exp(ims_temp[which(ims_temp$accession==temp_acession),]$mean_h)-1))
  for (j in temp_acession) {
    temp = ims_temp[which(ims_temp$accession == j),]
    mean_dm =  temp[which.min(abs(as.numeric(temp$diff_mean) - as.numeric(lcms_rrho[which(lcms_rrho[, 1] == j), 2]))),]$diff_mean
    ##############
    ims_matched[which(ims_matched$accession == j),]$diff_mean = mean_dm
  }
  
  test = data.frame(
    ac = cbind(
      ims_matched$accession,
      dm = ims_matched$diff_mean,
      hmdb = ims_matched$mz_hmdb,
      detected_mz = ims_matched$exp_mz
    )
  )
  #### fiNAL MUTUAL MATCH
  ims_rrho = ims_rrho[which(ims_rrho[, 1] %in% lcms_rrho[, 1]),]
  
  # plot
  if (nrow(ims_rrho) <= 10) {
    RRHO_obj <-
      RRHO2_initialize(
        ims_rrho,
        lcms_rrho,
        stepsize = 5,
        labels = c("ims", "lcms"),
        log10.ind = F,
        method = "hyper"
      )
  } else{
    RRHO_obj <-
      RRHO2_initialize(
        ims_rrho,
        lcms_rrho,
        stepsize = 3,
        labels = c("ims", "lcms"),
        log10.ind = F,
        method = "hyper"
      )
  }
  
  svglite::svglite(paste0(i, ".svg"), width = 6, height = 4)
  RRHO2_heatmap(
    x = seq(
      min(ims_rrho[, 2]),
      max(ims_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    y = seq(
      min(lcms_rrho[, 2]),
      max(lcms_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    RRHO_obj,
    main = i
  )
  
  RRHO2_heatmap(
    x = seq(
      min(ims_rrho[, 2]),
      max(ims_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    y = seq(
      min(lcms_rrho[, 2]),
      max(lcms_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    RRHO_obj,
    main = i
  )
  dev.off()
  ########### get analytic table
  uu = getPathwayFromAnalyte(paste0("HMDB:", RRHO_obj$genelist_uu$gene_list_overlap_uu))
  uu = uu[!duplicated(uu$pathwayName),]
  uu_comparason_table = data.frame(
    HMDB = RRHO_obj$genelist_uu$gene_list_overlap_uu,
    `logFC(Cancer versus normal) IMS` = ims_rrho[which(ims_rrho[, 1] %in% RRHO_obj$genelist_uu$gene_list_overlap_uu), 2],
    `logFC(Cancer versus normal) LCMS` = lcms_rrho[which(lcms_rrho[, 1] %in% RRHO_obj$genelist_uu$gene_list_overlap_uu), 2],
    `Metabolite name` = unlist(
      lapply(RRHO_obj$genelist_uu$gene_list_overlap_uu, function(x) {
        temp = uu[which(grepl(pattern = x,
                              uu$inputId)),]$commonName[1]
        return(temp)
      })
    ),
    `Common trend` = rep(
      "Both upregulated in tumour",
      times = length(RRHO_obj$genelist_uu$gene_list_overlap_uu)
    ),
    `Detected matrix` = rep(i, times = length(
      RRHO_obj$genelist_uu$gene_list_overlap_uu
    ))
  )
  ## downdown
  dd = getPathwayFromAnalyte(paste0("HMDB:", RRHO_obj$genelist_dd$gene_list_overlap_dd))
  dd = dd[!duplicated(dd$pathwayName),]
  dd_comparason_table = data.frame(
    HMDB = RRHO_obj$genelist_dd$gene_list_overlap_dd,
    `logFC(Cancer versus normal) IMS` = ims_rrho[which(ims_rrho[, 1] %in% RRHO_obj$genelist_dd$gene_list_overlap_dd), 2],
    `logFC(Cancer versus normal) LCMS` = lcms_rrho[which(lcms_rrho[, 1] %in% RRHO_obj$genelist_dd$gene_list_overlap_dd), 2],
    `Metabolite name` = unlist(
      lapply(RRHO_obj$genelist_dd$gene_list_overlap_dd, function(x) {
        temp = dd[which(grepl(pattern = x,
                              dd$inputId)),]$commonName[1]
        return(temp)
      })
    ),
    `Common trend` = rep(
      "Both downregulated in tumour",
      times = length(RRHO_obj$genelist_dd$gene_list_overlap_dd)
    ),
    `Detected matrix` = rep(i, times = length(
      RRHO_obj$genelist_dd$gene_list_overlap_dd
    ))
  )
  temp_comparason_table = rbind(uu_comparason_table,
                                dd_comparason_table)
  comparason_table = rbind(comparason_table,
                           temp_comparason_table)
}

for (i in 1:nrow(comparason_table)) {
  if (is.na(comparason_table[i,]$Metabolite.name)) {
    comparason_table[i,]$Metabolite.name = unique(ims_sm[which(ims_sm$accession == comparason_table[i,]$HMDB),]$name)[1]
  }
}
write.csv(comparason_table,
          file = "Common_up_down_regulated_small_molecule_metabolites_in_ims.csv")


for (i in unique(matrix_polarity)) {
  image[[i]] = image_read_svg(paste0(i, ".svg")) |> image_ggplot()
}
svglite::svglite(paste0("all.svg"), width = 10, height = 15)
gridExtra::grid.arrange(image[[1]],
                        image[[2]],
                        image[[3]],
                        image[[4]],
                        image[[5]],
                        image[[6]],
                        image[[7]],
                        image[[8]],
                        image[[9]],
                        image[[10]],
                        ncol = 2)
dev.off()

#save(RRHO2_heatmap, file = "RRHO_heatmap.Rdata")
#########################################################
matched_hmdb = all_matched

ratio_df = data.frame()
for (i in 1:length(all_matched)) {
num_matched_hmdb = nrow(all_matched[[i]])
num_matched_same_direction_hmdb = length(which(comparason_table$Detected.matrix == names(all_matched)[i]))
ratio_df = rbind(
ratio_df,
rbind(
data.frame(
num_matched_hmdb = num_matched_hmdb - num_matched_same_direction_hmdb,
num_matched_lcms = 145,
matrix = names(all_matched)[i],
marker = "All matched metabolites"
)
),
data.frame(
num_matched_hmdb = num_matched_same_direction_hmdb,
num_matched_lcms = 145,
matrix = names(all_matched)[i],
marker = "Matched metabolites of same direction"
)
)
}
# Annotate plot
# convert_value  = function(x,range){
#   x = as.numeric(x)
#   range = as.numeric(range())
#   ratio = (max(x)-min(x))/(max(range)-min(range))
#   newx = (x-min(x))/ratio+min(range)
#   return(newx)
# }
# #
# CHCA2 = comparason_table[which(comparason_table$Detected.matrix == "CHCA sublimation (2step)+"),]
# lcmsfc =as.numeric(CHCA2$logFC.Cancer.versus.normal..LCMS)
# imsfc = as.numeric(CHCA2$logFC.Cancer.versus.normal..IMS)
# 
# chca_plotdf =rbind(CHCA2 %>% select(Metabolite.name)%>%
#                      mutate(logfc = convert_value(x = lcmsfc, range=c(min(lcmsfc)/(max(lcmsfc)-min(lcmsfc)),
#                                                                       max(lcmsfc)/(max(lcmsfc)-min(lcmsfc))))) %>% 
#                      mutate(label = rep("lcms", times = nrow(CHCA2))) %>% 
#                      set_colnames(c("name","logfc","label")),
#                    CHCA2 %>% select(Metabolite.name,)%>%
#                      mutate(logfc = convert_value(x = imsfc, range=c(min(imsfc)/(max(imsfc)-min(imsfc)),
#                                                                       max(imsfc)/(max(imsfc)-min(imsfc))))) %>% 
#                      mutate(label = rep("ims", times = nrow(CHCA2))) %>% 
#                      set_colnames(c("name","logfc","label")))
# ####### rrho2 plot
# # ims =cbind(chca_plotdf[which(chca_plotdf$label == "ims"),]$name,chca_plotdf[which(chca_plotdf$label == "ims"),]$logfc)
# # 
# # lcms =cbind(chca_plotdf[which(chca_plotdf$label == "lcms"),]$name,chca_plotdf[which(chca_plotdf$label == "lcms"),]$logfc)
# chca2 = matched_hmdb[[7]]
# ims = cbind(chca2$HMDB, chca2$diff_ims)
# lcms = cbind(chca2$HMDB, chca2$diff_lcms)
# OBJ = RRHO2_initialize(
#         ims,
#         lcms,
#         stepsize = 3,
#         labels = c("ims", "lcms"),
#         log10.ind = F,
#         method = "hyper"
# )
# dev.off()
# RRHO2_heatmap(OBJ)
# #################
# setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
# tiff(file="rrho_lcms_ims_CHCA2s.jpg",
#      units="in", width=6, height=6, res=500,compression = "lzw")
# RRHO2_heatmap(OBJ)
# dev.off()
# img <- image_read("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2/CHCA(2STEP_LCMS_IMS_METABOLITES).png")
# #######################
# annotate_bar = ggplot(data = chca_plotdf,
#                       aes(x = name, y = as.numeric(logfc),fill = label)) +
#   
#   geom_bar(stat = "identity",
#            position = "dodge")+
#   scale_fill_manual()+
#   ggtitle("The log fold change of the metabolites in tumour")+
#   xlab("m/z") + ylab("Proportion of wasserstein distance explained (%)")+ theme_bw()
#
############################### 
temp = ggplot(
ratio_df,
aes(
fill = matrix,
y = num_matched_hmdb/num_matched_lcms*100,
x = factor(matrix, level = c("9AA Sublimation-",
                             "9AA Sublimation(2step)-" ,
"9AA Sublimation+" ,
"9AA Sublimation(2step)+",
"CHCA sublimation-",
"CHCA sublimation (2step)-",
"CHCA sublimation+",
"CHCA sublimation (2step)+" ,
"DHB Sublimation-",
                                                        "DHB Sublimation+")),
pattern = marker
)
) +
geom_bar(position = "stack", stat = "identity") +
geom_bar_pattern(
position = "stack",
stat = "identity",
color = "black",
pattern_fill = "black",
pattern_angle = 45,
pattern_density = 0.1,
pattern_spacing = 0.025,
pattern_key_scale_factor = 0.6
) +
scale_pattern_manual(
values = c(
`Matched metabolites of same direction` = "stripe",
`All matched metabolites` = "none"
)
) +
scale_fill_manual(values = rep(
c(
"9AA Sublimation-"="#007AB6",
                                                         "9AA Sublimation+" = "#ABC7E6",
                                                         "9AA Sublimation(2step)-"="#413975",
                                                         "9AA Sublimation(2step)+"= "#9068AC",
                                                         "DHB Sublimation-"="#F77800",
                                                         "DHB Sublimation+"="#FDB772",
                                                         "CHCA sublimation (2step)-"= "#2FA143",
                                                         "CHCA sublimation (2step)+"="#5AC096",
                                                         "CHCA sublimation-"="#916729",
                                                         "CHCA sublimation+"="#C3A128"
),
each = 1
), guide = "none") +
labs(x = "Matrix/Polarity combinations", y = "Percentage of overlapping metabolites with LCMS (%)", pattern = "Whether the overlapping metabolites \n detected in IMS has same regulatory direction \n as the one detected in LCMS") +
ggtitle("Ratio of overlapping metabolites with LCMS for each IMS matrices") +theme_bw()+ theme(
panel.grid.major = element_blank(),
panel.grid.minor = element_blank()) +scale_x_discrete(guide=guide_axis(n.dodge=2)) + annotation_custom(rrho)

setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(
filename = "Figure2B.svg",
plot = temp,
width = 13,
height = 6 * 1.618,
dpi = 600
)
```

```{r figure2c}
data = data[which(data$Tissue == "Tissue1"),]
matrix_polarity = paste0(data$matrix,data$polarity)
#
if(length(grep(colnames(data), pattern = "matrix_polarity")) == 0){
  data = cbind(data, matrix_polarity)
}
## Find unique hmdb ids
unique_id = unique(data$chemical_formula)
###
#unique_id = unique(data$accession)


# create matrix_attri to help create upsetR plot
## nn = number of top expressed metabolites we want select
View(matrix_attri)
nn = length(unique_id)
matrix_attri = data.frame(matrix(0,nrow = nn, ncol =length(unique(data$matrix_polarity))))
colnames(matrix_attri) = unique(data$matrix_polarity)
for (i in 1:nn){
  #make a temprory matrixname stores the polar+matrix name with matched HMDB id
  matrixname = unique(data[which(data$chemical_formula==unique_id[i]),]$matrix_polarity)
  #matrixname = unique(data[which(data$accession==unique_id[i]),]$matrix_polarity)
  for(j in 1:length(matrixname)){
    # for each row, if the matrix name is matched with colname of matrix_attri, then the slot has 1 
    matrix_attri[i,which(colnames(matrix_attri)==matrixname[j])]=1
  }
}
# plot upserR


a= upset(matrix_attri,
             colnames(matrix_attri),
             #mainbar.y.label = "Number of uniquely detected m/z peaks",
             group_by='degree',
             width_ratio=0.1,
         min_size = 20,
        sort_intersections_by = c('degree','cardinality'),
        matrix=(
        intersection_matrix(geom=geom_point(shape='circle filled', size=2))+ 
          scale_color_manual(
          values=c("9AA Sublimation-"="#007AB6",
                                                         "9AA Sublimation+" = "#ABC7E6",
                                                         "9AA Sublimation(2step)-"="#413975",
                                                         "9AA Sublimation(2step)+"= "#9068AC",
                                                         "DHB Sublimation-"="#F77800",
                                                         "DHB Sublimation+"="#FDB772",
                                                         "CHCA sublimation (2step)-"= "#2FA143",
                                                         "CHCA sublimation (2step)+"="#5AC096",
                                                         "CHCA sublimation-"="#916729",
                                                         "CHCA sublimation+"="#C3A128"),
          # values=c('9AA-'="#007AB6",
          #          '9AA+'="#ABC7E6",
          #          'CHCA(2step)+'="#5AC096",
          #          'CHCA(2step)-'="#2FA143"
          #          ),
          guide=guide_legend(override.aes=list(shape='circle'))
        )
      ),
      queries=list(
        upset_query(set='9AA Sublimation-', fill='#007AB6'),
        upset_query(set='9AA Sublimation+', fill='#ABC7E6'),
        upset_query(set='9AA Sublimation(2step)-', fill='#413975'),
        upset_query(set='9AA Sublimation(2step)+', fill='#9068AC'),
        upset_query(set='DHB Sublimation+', fill ='#FDB772'),
        upset_query(set='DHB Sublimation-', fill ='#F77800'),
        upset_query(set='CHCA sublimation (2step)+', fill ='#5AC096'),
        upset_query(set='CHCA sublimation (2step)-', fill ='#2FA143'),
        upset_query(set='CHCA sublimation+', fill ='#C3A128'),
        upset_query(set='CHCA sublimation-', fill ='#916729')
      ),

      #Lipid
      # queries=list(
      #   upset_query(set='9AA-', fill='#007AB6'),
      #   upset_query(set='9AA+', fill='#ABC7E6'),
      #   upset_query(set='CHCA(2step)+', fill ='#5AC096'),
      #   upset_query(set='CHCA(2step)-', fill ='#2FA143')
      # ),
      base_annotations=list(
        'Intersection size'=intersection_size(
          text_colors=c(
            on_background='brown', on_bar='green'
          ),
          text = list(
          size = 0,
          vjust = -2
          )
        )+ 
          annotate(
          geom='text', x=Inf, y=Inf,
          label=paste('Total:', nrow(matrix_attri)),
          vjust=1, hjust=1
        )+ 
          ylab('Intersection Size')+
          ggtitle('Unique matched chemical formula found in ROI of matrix/polarity intersections')+
          theme_bw()+ theme(
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
      ),
      themes=upset_modify_themes(
        list(
          'Intersection Size'=theme(text=element_text(
            size=13, angle = 90)),
          'overall_sizes'=theme(axis.text.x=element_text(angle=90))
        )
      )
    )

##############################################################

# ggsave(filename = "Overalp_between_matched_mz_generated_Tissue2.svg",
#        plot = a,
#        width=6*1.681, height=6)

setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(filename = "Figure2C.svg",
       plot = a,
       width=6*1.681, height=6)
```



```{r figure2d}
setwd("~/paper/Optimisation/ORA_Enrichment_Tissue1_general_background")
temp = list.files(pattern="*name_version.csv")
myfiles = lapply(temp, read.csv)
myfiles = lapply(myfiles, function(x){
  x = x[,1:10]
  return(x)
}
)


######################################################################### 
############################################ Use RAMP intrinsic function
# Create an entry with polarity and matrix

####### query database
query <- "select * from analytehaspathway"
con <- connectToRaMP()
allids <- RMariaDB::dbGetQuery(con, query)
RMariaDB::dbDisconnect(con)
kegg_met_allids = subset(allids, pathwaySource == "kegg" & grepl(rampId, pattern ="RAMP_C"))

kegg_identifier = read.csv("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/human/Kegg_pathway_identifier/kegg_classifier.csv")
######################
for(i in 1:10){
  data_r= data[which(data$matrix_polarity == unique(matrix_polarity)[i]),]
  data_r= data_r[!duplicated(data_r$accession),]
  # only operate once
  data_r$accession = paste("hmdb:",data_r$accession,sep="")
  data_r$cas_registry_number = paste("CAS:",data_r$cas_registry_number,sep="")
  data_r$chebi_id = paste("chebi:",data_r$chebi_id,sep="")
  data_r$chemspider_id = paste("chemspider:",data_r$chemspider_idxx,sep="")
  # Create a sample
  pmatrixname = unique(data_r$matrix)
  search= unique(rbind(data.frame(analytes = data_r$accession),
                       data.frame(analytes =subset(data_r$cas_registry_number,nchar(data_r$cas_registry_number)>=5)),
                       data.frame(analytes =subset(data_r$chebi_id,nchar(data_r$chebi_id)>=7)),
                       data.frame(analytes =subset(data_r$chemspider_id,nchar(data_r$hemspider_id)>=12))))
  fisher.results <- RaMP:::runCombinedFisherTest(search, NameOrIds = "ids", total_genes = 20000, 
                                                 MCall = F, alternative = "less", min_path_size = 0, 
                                                 max_path_size = 150000, background_type = "database", 
                                                 background = "database", pathway_definitions = "RaMP")
  #filtered.fisher.results <- FilterFishersResults(fisher.results, pval_type = 'fdr', pval_cutoff=0.05)
  filtered.fisher.results = fisher.results[[1]][which(fisher.results[[1]]$pathwaySource == "kegg"),] %>%
    mutate(id_short = sub("map","",pathwayId) ) %>%
    mutate(  `kegg classifier` = unlist(lapply(id_short, function(x){
      temp = kegg_identifier[which(grepl(pattern = x, kegg_identifier$id)),]$group
      if(length(temp)!=0){
        return(temp) 
      }else{
        temp = "Deleted pathways from Kegg"
      }
    }
    )))%>%
    relocate(`kegg classifier`)
  
  # recalculate the significance
  
  # clusters <- RaMP::findCluster(filtered.fisher.results,
  #                               perc_analyte_overlap = 0.3,
  #                               min_pathway_tocluster = 2, perc_pathway_overlap = 0.2
  # )
  #results = clusters$fishresults %>% mutate_if(is.numeric, ~ round(., 8))
  results = filtered.fisher.results %>% mutate_if(is.numeric, ~ round(., 8))
  ########### append our detected metabolites
  pathwaydf <- getPathwayFromAnalyte(search, includeRaMPids = TRUE, 
                                     NameOrIds = "ids", find_synonym = FALSE)
  filtered_df = pathwaydf[which(pathwaydf$pathwayId %in%  results$pathwayId), ]
  
  # Recalculated p-val
  
  pval =c()
  for(j in 1:nrow(results)){
    total_in_pathway = results$Total_In_Path[j]
    in_data_in_pathway = results$Num_In_Path[j]
    not_in_data_in_pathway = total_in_pathway -  in_data_in_pathway
    in_data_outside_pathway = length(unique(filtered_df$rampId)) -  in_data_in_pathway
    outside_both= length(which(grepl(pattern = "RAMP_C",unique(allids[which(allids$pathwayRampId %in% unique(filtered_df$pathwayRampId)),]$rampId)))) - total_in_pathway - in_data_outside_pathway
    conti_table = data.frame(
      "in_pathway" = c(in_data_in_pathway,not_in_data_in_pathway ),
      "not_in_pathway" = c(in_data_outside_pathway, outside_both ),
      row.names = c("Detected metabolites", "Not detected metabolites"),
      stringsAsFactors = FALSE
    )
    fisher = fisher.test(conti_table, alternative = "greater")
    pval[j] = fisher$p.value
  }
  
  results_final = results %>% 
    mutate(Pval = pval) %>% 
    mutate(Pval_FDR = p.adjust(pval, method = "fdr"))%>% 
    mutate(Pval_Holm = p.adjust(pval, method = "holm")) %>%
    mutate(`Detected versus pathway total ratio` =Num_In_Path/Total_In_Path )%>%
    dplyr::select(-c("id_short","analytes","pathwaySource"))%>%
    rename("kegg_pathwayname"="pathwayName" )%>%
    relocate(`Detected versus pathway total ratio`)%>%
    relocate(`kegg classifier`) %>%
    arrange(Pval)
  
  #########################
  
  name = c()
  for(j in results_final$pathwayId){
    commonname = sub("*;.*","",unique(filtered_df[which(filtered_df$pathwayId==j),]$commonName))
    name = c(name,paste(commonname, collapse = ";\n"))
  }
  results_f = cbind(results_final, Detected_metabolites = name)
  write.csv(results_f, file= paste0( unique(matrix_polarity)[i],"_ORA_enrichment_results_kegg_version.csv"))
  results_f_s = results_f %>% dplyr::select(-Detected_metabolites)
  write.csv(results_f_s, file= paste0( unique(matrix_polarity)[i],"_ORA_enrichment_results_kegg_no_metabolites_name_version.csv"))

}
  ##############################################################################################



# Make a data.frame to store graphing stuff
matrixId = c("9AA-",
             "9AA-(Recrystallisation)",
             "9AA+(Recrystallisation)",
             "9AA+",
             "CHCA-(Recrystallisation)",
             "CHCA+(Recrystallisation)",
             "CHCA-",
             "CHCA+",
             "DHB-",
             "DHB+")
plotdf = data.frame()
for(i in 1:length(myfiles)){
  tempdf = cbind("Pathways" = myfiles[[i]]$kegg_pathwayname,
                 "Matrix" = rep(matrixId[i],length(myfiles[[i]]$kegg_pathwayname)),
                 "pval" = myfiles[[i]]$Pval,
                 "fdr_pval" = myfiles[[i]]$Pval_FDR,
                 "holm_pval" = myfiles[[i]]$Pval_Holm,
                 "id" = myfiles[[i]]$pathwayId,
                 "Classifier" = myfiles[[i]]$kegg.classifier,
                 "ratio" = myfiles[[i]]$Detected.versus.pathway.total.ratio
                 )
  plotdf = rbind(plotdf,tempdf)
}
################################################################################
View(plotdf)
plotdf[which(plotdf$Pathways == "Androgen and Estrogen Metabolism"),]$Classifier = "5.2 Endocrine system"
plotdf[which(plotdf$Pathways == "Steroidogenesis"),]$Classifier = "5.2 Endocrine system"
plotdf[which(plotdf$Pathways == "D-Arginine and D-Ornithine Metabolism"),]$Classifier = "1.6 Metabolism of other amino acids"
#
#plotdf = plotdf[-which(plotdf$Classifier == "Deleted pathways from Kegg"),]



############
# ggplot(data=plotdf, aes(Matrix, Pathways,colour = FDR_pval)) + geom_point()
# dev.off()
# library(ggplot2)
# 
# plotdf$Cluster = sapply(plotdf$Pathways,function(x){ 
#                  temp = clusters[["fishresults"]][["cluster_assignment"]][which(clusters[["fishresults"]][["pathwayName"]]%in%x)]
#                  return(temp)
#                  })
## Small molecule tissue 2
# pathway_df =  plotdf
# pathway_df[which(pathway_df$Cluster == "6, 11"),]$Cluster = 6
# pathway_df[which(pathway_df$Cluster == "6, 12"),]$Cluster = 6
# pathway_df[which(pathway_df$Cluster == "5, 6"),]$Cluster = 5
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "Glycogen",ignore.case = T) 
#                  | grepl(pathway_df$Pathway,pattern = "Glu",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "cori",ignore.case = T)),]$Cluster = 2
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "nucleotide",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "purine",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "Methionine",ignore.case = T)),]$Cluster = 3
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "slc",ignore.case = T)),]$Cluster = 1
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "fatty acid",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "cholestoeol",ignore.case = T)),]$Cluster = 4
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "amino acid",ignore.case = T)),]$Cluster = 5
# 
# plotdf =pathway_df
# ####################### Setting colours
cols <- c("Carbohydrate metabolism"= '#0f7321',
          "Energy metabolism"='#f23a34',
          "Lipid metabolism"='#008080',
          "Nucleotide metabolism"='#0069b4',
          "Amino acid metabolism"='#00ffff',
          "Metabolism of other amino acids"='#ffa731',
          "Metabolism of cofactors and vitamins"='#fa2b73',
          "Biosynthesis of other secondary metabolites"= '#f072d4',
          "Endocrine system" = "#0fd214"
)
plotdf = plotdf %>% mutate(group =sub(" ","",sub(".*[0-9]","",sub(".*.[1-9]","",plotdf$Classifier))))%>%
mutate(significance = ifelse(as.numeric(pval)<=0.1, "Significant at 10% significance level",
                                        "Not statistically significant"))
cols = unlist(cols)
cols <- data.frame(color = unlist(cols),
                   group = names(unlist(cols)))

plotdf <- merge(plotdf, cols, by = "group", all.x = TRUE)
plotdf$Pathways_colour <- paste0("<span style=\"color: ",plotdf$color, "\">",plotdf$Pathways, "</span>")

plotdf = plotdf[!duplicated(plotdf[,2:3]),]

# Get most significant pathways
n = 50
filtered_df = data.frame()
for(i in 1:length(unique(plotdf$Matrix))){
  temp = plotdf[which(plotdf$Matrix == unique(plotdf$Matrix)[i]),]
  if(nrow(temp)>=n){
    temp = temp[order(temp$pval, decreasing = FALSE),][1:10,]
  }else{
    temp = temp[order(temp$pval, decreasing = FALSE),][1:nrow(temp),]
  }
  if( i == 1){
    filtered_df = temp
  }else{
    filtered_df = rbind(filtered_df, temp) 
  }
}
##############################

temp = ggplot(data=na.omit(plotdf), aes(x = factor(Matrix, level = c("9AA-",
                                                                     "9AA-(Recrystallisation)",
                                                                       "9AA+",
                                                                       "9AA+(Recrystallisation)",
                                                                       "CHCA-",
                                                                        "CHCA-(Recrystallisation)",
                                                                     "CHCA+",
                                                                       "CHCA+(Recrystallisation)",
                                                                      "DHB-",
                                                                       "DHB+")), y = Pathways_colour, fill = group))+ 
       geom_point(aes(colour = as.numeric(pval),size = as.numeric(ratio)))+
  scale_colour_distiller(name="P value" 
                         ,palette = 'BuGn',
                         limits = c(0, 1), breaks = seq(0,1,0.2),
                         direction= -1)+
  scale_size_continuous(name = "Ratio of detected metabolites")+
  new_scale_colour() +
       geom_point(shape=1,aes(colour = significance,size =as.numeric(ratio) ))+
  scale_color_manual(values = c("Significant at 10% significance level" = "red",
                                "Not statistically significant" = "black"))+
   labs(
         title = "Comparason of pathways between different matrices",
         y = "Pathways", x = "Matrices molecule/polarity")+
       theme(title =element_text(size=15, face='bold'),
         axis.text.x = element_text(size = 12,
                                  angle =90,
                                  vjust = 0.5, hjust=1,
                                  colour = c('9AA-'="#007AB6",
                                             '9AA-(Recrystallisation)'= "#413975",
                                             '9AA+'="#ABC7E6",
                                             '9AA+(Recrystallisation)'="#9068AC",
                                             'CHCA-'="#916729",
                                             'CHCA-(Recrystallisation)'="#2FA143",
                                             'CHCA+'="#C3A128",
                                             'CHCA+(Recrystallisation)'="#5AC096",
                                             'DHB-' ="#F77800",
                                             'DHB+' ="#FDB772"
                                    )),#20
            axis.title = element_text(size = 9),#40
            axis.text.y = element_markdown(size = 9),
            legend.key.size = unit(1, 'cm'),
            legend.title = element_text(size=9),
            legend.text = element_text(size=9))+
  new_scale_colour() + theme(panel.background = element_rect(fill = "white"),
                                               panel.grid = element_line(color = "grey")) +
  geom_tile(aes(fill = group), colour = "white",
            width= 0 ,
            height = 0) + 
  scale_fill_manual(values  = c("Carbohydrate metabolism"= '#0f7321',
          "Energy metabolism"='#f23a34',
          "Lipid metabolism"='#008080',
          "Nucleotide metabolism"='#0069b4',
          "Amino acid metabolism"='#00ffff',
          "Metabolism of other amino acids"='#ffa731',
          "Metabolism of cofactors and vitamins"='#fa2b73',
          "Biosynthesis of other secondary metabolites"= '#f072d4',
          "Endocrine system" = "#0fd214"),
  drop = F,
  name = 'the kegg classifier')
  
# save image
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(filename = "Figure2D_modified.svg",
       plot = temp,
       width=10, height=14)
```

```{r supplyf2A}
# num stores the number of unique detected small molecules, num_mz, number of unique m/z s
#Annotate plot
convert_value  = function(x,range){
  x = as.numeric(na.omit(x))
  range = as.numeric(na.omit(range))
  ratio = (max(x)-min(x))/(max(range)-min(range))
  newx = (x-min(x))/ratio+min(range)
  return(newx)
}
#
for(i in unique(comparason_table$Detected.matrix)){
  i  = unique(comparason_table$Detected.matrix)[5]
CHCA2 = comparason_table[which(comparason_table$Detected.matrix == i),]
lcmsfc =as.numeric(CHCA2$logFC.Cancer.versus.normal..LCMS)
imsfc = as.numeric(CHCA2$logFC.Cancer.versus.normal..IMS)

chca_plotdf =rbind(CHCA2 %>% select(Metabolite.name)%>%
                     mutate(logfc = convert_value(x = lcmsfc, range=c(min(lcmsfc)/(max(lcmsfc)-min(lcmsfc)),
                                                                      max(lcmsfc)/(max(lcmsfc)-min(lcmsfc))))) %>%
                     mutate(label = rep("lcms", times = nrow(CHCA2))) %>%
                     set_colnames(c("name","logfc","label")),
                   CHCA2 %>% select(Metabolite.name,)%>%
                     mutate(logfc = convert_value(x = imsfc, range=c(min(imsfc)/(max(imsfc)-min(imsfc)),
                                                                      max(imsfc)/(max(imsfc)-min(imsfc))))) %>%
                     mutate(label = rep("ims", times = nrow(CHCA2))) %>%
                     set_colnames(c("name","logfc","label")))
####### rrho2 plot
# ims =cbind(chca_plotdf[which(chca_plotdf$label == "ims"),]$name,chca_plotdf[which(chca_plotdf$label == "ims"),]$logfc)
# lcms =cbind(chca_plotdf[which(chca_plotdf$label == "lcms"),]$name,chca_plotdf[which(chca_plotdf$label == "lcms"),]$logfc)
chca2 = matched_hmdb[[i]]
ims = cbind(chca2$HMDB, chca2$diff_ims)
lcms = cbind(chca2$HMDB, chca2$diff_lcms)

OBJ = RRHO2_initialize(
        ims,
        lcms,
        stepsize = 1,
        labels = c("ims", "lcms"),
        log10.ind = F,
        method = "hyper"
)

#######################
annotate_bar = ggplot(data = chca_plotdf,
                      aes(x = name, y = as.numeric(logfc),fill = label)) +
  geom_bar(stat = "identity",
           position = "dodge")+
  scale_fill_manual(values = c("lcms" = "blue",
                               "ims" = "red"))+
  ggtitle(paste0("Scaled log fold change betwen lcms and ims"), )+
  xlab("Metabolites' name") + ylab("The scaled log fold change of the metabolites in tumour")+ theme_bw() +coord_flip() + theme_bw()+ theme(
panel.grid.major = element_blank(),
panel.grid.minor = element_blank())
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2/Supply2A")
ggsave(filename = paste0(i,"overlapping_metabolites.svg"),
       plot = annotate_bar,
       width=10, height= length(chca_plotdf$name)/6)
###############################
#################
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2/Supply2A")
tiff(file=paste0(i,"rrho_lcms_ims_same_direction.jpg"),
     units="in", width=6, height=6, res=500,compression = "lzw")
RRHO2_heatmap(OBJ)
dev.off()
}

```


```{r supplyf2b}
files = list.files(path = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output",
                   pattern = "RDS")
moi_list = c("D-Glucose",
             "Glucose-6-glutamate",
             "L-Glutamine",
             "D-Glutamine",
             "L-Glutamic acid",
             "DL-Glutamate",
             "D-threo-isocitrate",
             "Taurine",
             "Ascorbic acid",
             "Glutathione",
             "Linoleic acid",
             "N-Acetyl-L-aspartic acid",
             "Inosine",
             "Uridine 5'-monophosphate",
             "Uridine"
             )
# names = unique(data[which(grepl(data$chemical_formula, pattern = "C9H14N2O12P2",ignore.case = T)),]$name)
# 
# names = unique(data[which(grepl(data$name, pattern = "uridine",ignore.case = T)),]$name)
# test = lapply(names, function(x){
#  temp = unique(data[which(data$name == x),]$matrix_polarity)
#  return(temp)
#    }
#  )
# names(test)=names
heatmap_df = data.frame()
for(i in unique(matrix_polarity)){
  #i = unique(matrix_polarity)[3]
  df = data[which(data$matrix_polarity == i),]
  temp = data.frame(unlist(lapply(moi_list, function(x){
    temp = mean(df[which(df$name==x),]$diff_mean)
    return(temp)
  }
  )
  ))
 temp = cbind(temp,moi_list,rep(i,times = length(moi_list)))
 colnames(temp) = c("diff_mean",
                    "Metabolites' list",
                    "Matrix")
 if(i == unique(matrix_polarity)[1]){
   heatmap_df= temp
 }else{
   heatmap_df = rbind(heatmap_df,temp)
 }
}
#plot
temp = ggplot(heatmap_df,aes(x=Matrix,
                      y=`Metabolites' list`,
                      fill = diff_mean)) +
  geom_tile(color = "black") +
  scale_fill_gradient2(low = "#075AFF",
                       high = "#FF0000") +
  coord_fixed()+
  theme(axis.text.x = element_text(angle = 90))

setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(filename = "SupF2B_reverse.svg",
       plot = temp,
       width=6, height=6*1.681)
```


```{r supplyf2c}
# Read files
setwd("~/paper/Optimisation/ORA_Enrichment_Tissue1_general_background")
temp = list.files(pattern="*name_version.csv",
                  recursive = F)
myfiles = lapply(temp, read.csv)
myfiles = lapply(myfiles, function(x){
  x = x[,1:10]
  return(x)
}
)
# src_file = "/stornext/Bioinf/data/lab_brain_cancer/users/t_lu/Optimisation"
# filenames <- list.files(path = paste0(src_file,"/ORA_Enrichment_Tissue1_general_background"), pattern="*.csv")
# myfiles = lapply(filenames, read.csv)

#
matrixId = c("9AA-",
             "9AA-(Recrystallisation)",
             "9AA+(Recrystallisation)",
             "9AA+",
             "CHCA-(Recrystallisation)",
             "CHCA+(Recrystallisation)",
             "CHCA-",
             "CHCA+",
             "DHB-",
             "DHB+")

plotdf = data.frame()
for(i in 1:length(myfiles)){
  tempdf = cbind(myfiles[[i]]$pathwayName,
                 rep(matrixId[i],length(myfiles[[i]]$pathwayName)),
                 myfiles[[i]]$Pval_FDR)
  plotdf = rbind(plotdf,tempdf)
}
# find clusters
total_datatable = do.call(rbind,myfiles[1:10])
total_datatable = (total_datatable[!duplicated(total_datatable$pathwayName),])[,colnames(total_datatable)!="cluster_assignment"]
total_datatable = list(fishresults = total_datatable,
                       analyte_type = "metabolites")

colnames(plotdf) = c("Pathways",
                     "Matrix",
                     "FDR_pval")
plotdf$FDR_pval = as.double(plotdf$FDR_pval)
plotdf$Cluster = sapply(plotdf$Pathways,function(x){ 
  temp = clusters[["fishresults"]][["cluster_assignment"]][which(clusters[["fishresults"]][["pathwayName"]]%in%x)]
  return(temp)
})
plotdf = plotdf[which(!duplicated(plotdf[,1:2])),]

plotdf[which(plotdf$Cluster == "1"),]$Pathways
################## get the matrix for upsetplot

pathway_df = data.frame(matrix(0, ncol=length(matrixId)+2, nrow = length(unique(plotdf$Pathways))))
colnames(pathway_df)= c(matrixId,"Cluster","Pathway_names")
for(i in 1: length(unique(plotdf$Pathways))){
  match = plotdf[which(plotdf$Pathways == unique(plotdf$Pathways)[i]),]$Matrix
  pathway_df[i,which(colnames(pathway_df) %in% match)] = 1
  pathway_df[i,length(matrixId)+1] = plotdf[which(plotdf$Pathways == unique(plotdf$Pathways)[i]),]$Cluster[1]
  pathway_df[i,length(matrixId)+2] = unique(plotdf$Pathways)[i]
}
## Small molecule tissue 2
## small molecule tissue 1
pathway_df[which(pathway_df$Cluster == "6, 7"),]$Cluster = 6
pathway_df[which(pathway_df$Cluster == "7,14"),]$Cluster = 14

#####################
cluster_name = c("Synaptic Neurotransmission",
                 "Hormone and fatty acid mediated insulin secretion",
                 "Sulfur amino acid (cysteine and homocysteine) metabolism",
                 "Glucose metabolism and catabolism",
                 "TP53 trancriptional regulation pathways",
                 "Glucose-transforming (Pentose and fructose) metabolism and increased oxdative stress",
                 "Glucose-transforming (Pentose and fructose) metabolism and increased oxdative stress",
                 "Nucleotide(Purine&Pyrimidine) biosynthesis and metabolism",
                 "Do not cluster",
                 "Amino acid metabolism and catabolism",
                 "SLC transporter disorders",
                 "Do not cluster",
                 "Do not cluster",
                 "Fatty acid transportation, metabolism and catabolism",
                 "Do not cluster")

index = naturalsort::naturalsort(unique(pathway_df$Cluster))
cluster_assign = c()
for(i in 1:length(cluster_name)){
  cluster_assign[which(pathway_df$Cluster == index[i])] =cluster_name[i]
}
pathway_df1 = cbind(pathway_df,"Cluster assignment of pathways" = cluster_assign)
#######################
cluster_name = c("SLC transporter disorders",
                 "Glucose metabolism and catabolism",
                 "Nucleotide metabolism and catabolism",
                 "Fatty acid transportation, metabolism and catabolism",
                 "Amino acid metabolism and catabolism",
                 "Nucleotide metabolism and catabolism",
                 "Do not cluster",
                 "DNA strand synthesis and elongation",
                 "Do not cluster"
                 )
index = naturalsort::naturalsort(unique(pathway_df$Cluster))
cluster_assign = c()
for(i in 1:length(cluster_name)){
  cluster_assign[which(pathway_df$Cluster == index[i])] =cluster_name[i]
}
pathway_df1 = cbind(pathway_df,"Cluster assignment of pathways" = cluster_assign)
library(ComplexUpset)

upset = upset(
  pathway_df1,
  matrixId,
  base_annotations=list(
    'Intersection size'=intersection_size(
      counts=FALSE,
      mapping=aes(fill=`Cluster assignment of pathways`))
    + scale_fill_manual(values=c(
      "SLC transporter disorders"='#a52a2a',
      "Glucose metabolism and catabolism"='#ffff00',
      "Nucleotide metabolism and catabolism"='#ff69b4',
      "Fatty acid transportation, metabolism and catabolism"='#008080',
      "Amino acid metabolism and catabolism"='#00ffff',
      "DNA strand synthesis and elongation" = '#ff692a',
      "Do not cluster" ='#aaaaaa'
    ))+
      ggtitle('Pathway analysis on metabolic profile generated for each matrix/polarity combination')
  ),
  group_by='degree',
  matrix=(
    intersection_matrix(geom=geom_point(shape='circle filled', size=2))
    + scale_color_manual(
      values=c('9AA-'="#007AB6", 
               '9AA+'="#ABC7E6",
               '9AA-(Recrystallisation)'= "#413975",
               '9AA+(Recrystallisation)'="#9068AC",
               'DHB+' ="#FDB772",
               'DHB-' ="#F77800",
               'CHCA+(Recrystallisation)'="#5AC096",
               'CHCA-(Recrystallisation)'="#2FA143",
               'CHCA+'="#C3A128",
               'CHCA-'="#916729"),
      guide=guide_legend(override.aes=list(shape='circle'))
    )
  ),
  queries=list(
    upset_query(set='9AA-', fill='#007AB6'),
    upset_query(set='9AA+', fill='#ABC7E6'),
    upset_query(set='9AA-(Recrystallisation)', fill='#413975'),
    upset_query(set='9AA+(Recrystallisation)', fill='#9068AC'),
    upset_query(set='DHB+', fill ='#FDB772'),
    upset_query(set='DHB-', fill ='#F77800'),
    upset_query(set='CHCA+(Recrystallisation)', fill ='#5AC096'),
    upset_query(set='CHCA-(Recrystallisation)', fill ='#2FA143'),
    upset_query(set='CHCA+', fill ='#C3A128'),
    upset_query(set='CHCA-', fill ='#916729')
  ),
  width_ratio=0.1
)
####
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(filename = "supplyf2C.svg",
       plot = upset,
       width=10*1.681, height=6)
```