---
title: "Figure5"
output: html_document
date: "2023-08-07"
---

```{r env}
.libPaths("/stornext/Bioinf/data/lab_brain_cancer/users/t_lu/R/x86_64-pc-linux-gnu-library/4.2")
library(ggplot2)
library(RaMP)
library(ggpattern)
library(Cardinal)
library(ggtext)
library(readxl)
library(RRHO2)
library(dplyr)
library(RaMP)
library(magick)
library(rsvg)
library(viridis)
library(ComplexUpset)
library(Cairo)
library(MASS) 
library(reshape2)
library(ggnewscale)
library(magrittr)
library(seriation)
library(cowplot)
library(stringr)
library(png)
library(RSEIS)
library(naturalsort)
# Set ramp connection
pkg.globals <- setConnectionToRaMP(
  dbname = "ramp", username = "root", conpass = "ADMIN",
  host = "localhost",socket = "/stornext/Home/data/allstaff/l/lu.t/mysql/var/run/mysqld/mysql.sock")
```

```{r figure5a}
src_path = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output"
long_file = naturalsort(list.files(src_path,
                        pattern = "potential_list_long.RDS"))

# num stores the number of unique detected small molecules, num_mz, number of unique m/z s
num = c()
num_mz = c()
num_backgroundmz = c()
#
#
name =  c("9AA Sublimation-(70-400)",NA,
                            "CHCA sublimation (2step)+(70-400)")
barplot = data.frame()
for(i in long_file[c(1,3)]){
  ind = which(long_file == i)
  data = readRDS(paste0(src_path,"/",i))
  num_mz[ind] = length(unique(data$exp_mz))
  num[ind] = length(unique(data$chemical_formula))
  
  temp = data.frame(cbind(c(num[ind],num_mz[ind]),
                     mp = rep(name[ind], times = 2)),
                     label = c(rep("Potential chemcial formulas matched", times = length(num[ind])),
                               rep("Experimental m/z", times = length(num[ind]))
                               #rep("Detected background peaks", times = length(num)))
                               )) 
  barplot = rbind(barplot,temp)
}
# barplot = store of the data
barplot = barplot %>% mutate(`type of analyte` = ifelse(grepl(mp,pattern = "70-400"), 
                                                    "Small molecules",
                                                    "Lipids"))
b = ggplot(data = barplot, aes(x = factor(mp, level = c("9AA Sublimation-(70-400)",
                            "CHCA sublimation (2step)+(70-400)")),y = as.integer(V1), fill = mp,pattern = label))+
  geom_bar_pattern(position = "dodge",
                   stat = "identity",
                   color = "black",
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6)+
  # scale_color_manual(values = c(
  #                           "Small molecules" = "black",
  #                           "Lipids" = "orange"))+
  scale_fill_manual(values = c(
                            "9AA Sublimation-(70-400)" = "#007AB6",
                            "CHCA sublimation (2step)+(70-400)" = "#5AC096"), guide = "none")+
 # scale_fill_manual(values = rep(c("#007AB6",
 #                                              "#ABC7E6",
 #                                              "#5AC096",
 #                                              "#2FA143"),each = 1), guide = "none")+
  scale_pattern_manual(values = c( `Experimental m/z` = "stripe", 
                                   `Potential chemcial formulas matched` = "none"))+
  labs(x = "Matrix/Polarity combinations", y = "Number of Detected Features", pattern = "Type of Feature") + 
  guides(pattern = guide_legend(override.aes = list(fill = "white")))+
  scale_x_discrete(guide = guide_axis(n.dodge = 1,
                                      angle = 90))+
  theme_bw()+ theme(axis.text.x = element_text(size = 7,
                                               colour =c("9AA Sublimation-(70-400)" = "#007AB6",
                            "CHCA sublimation (2step)+(70-400)" = "#5AC096"
                                                         )),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())  
# Save image 
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure5")
ggsave(filename = "Figure5A_small_molecule.svg",
       plot = b,
       width=4*1.681, height=6)



# num stores the number of unique detected small molecules, num_mz, number of unique m/z s
num = c()
num_mz = c()
num_backgroundmz = c()
#
#
name =  c(NA,"9AA Sublimation-(400-1000)",NA,
          "CHCA sublimation (2step)+(400-1000)")
barplot = data.frame()
for(i in long_file[c(2,4)]){
  ind = which(long_file == i)
  data = readRDS(paste0(src_path,"/",i))
  num_mz[ind] = length(unique(data$exp_mz))
  num[ind] = length(unique(data$chemical_formula))
  
  temp = data.frame(cbind(c(num[ind],num_mz[ind]),
                     mp = rep(name[ind], times = 2)),
                     label = c(rep("Potential chemcial formulas matched", times = length(num[ind])),
                               rep("Experimental m/z", times = length(num[ind]))
                               #rep("Detected background peaks", times = length(num)))
                               )) 
  barplot = rbind(barplot,temp)
}
# barplot = store of the data
barplot = barplot %>% mutate(`type of analyte` = ifelse(grepl(mp,pattern = "70-400"), 
                                                    "Small molecules",
                                                    "Lipids"))
b = ggplot(data = barplot, aes(x = factor(mp, level = c("9AA Sublimation-(400-1000)",
          "CHCA sublimation (2step)+(400-1000)")),y = as.integer(V1), fill = mp,pattern = label))+
  geom_bar_pattern(position = "dodge",
                   stat = "identity",
                   color = "black",
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6)+
  # scale_color_manual(values = c(
  #                           "Small molecules" = "black",
  #                           "Lipids" = "orange"))+
  scale_fill_manual(values = c( "9AA Sublimation-(400-1000)" = "#007AB6",
                            "CHCA sublimation (2step)+(400-1000)" = "#5AC096"), guide = "none")+
 # scale_fill_manual(values = rep(c("#007AB6",
 #                                              "#ABC7E6",
 #                                              "#5AC096",
 #                                              "#2FA143"),each = 1), guide = "none")+
  scale_pattern_manual(values = c( `Experimental m/z` = "stripe", 
                                   `Potential chemcial formulas matched` = "none"))+
  labs(x = "Matrix/Polarity combinations", y = "Number of Detected Features", pattern = "Type of Feature") + 
  guides(pattern = guide_legend(override.aes = list(fill = "white")))+
  scale_x_discrete(guide = guide_axis(n.dodge = 1,
                                      angle = 90))+
  theme_bw()+ theme(axis.text.x = element_text(size = 7,
                                               colour =c("9AA Sublimation-(400-1000)" = "#007AB6",
                            "CHCA sublimation (2step)+(400-1000)" = "#5AC096")),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())  
# Save image 
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure5")
ggsave(filename = "Figure5A_lipid.svg",
       plot = b,
       width=4*1.681, height=6)
```

```{r figure5b}
######################################################################### 
############################################ Use RAMP intrinsic function
# Create an entry with polarity and matrix

####### query database
query <- "select * from analytehaspathway"
con <- connectToRaMP()
allids <- RMariaDB::dbGetQuery(con, query)
RMariaDB::dbDisconnect(con)
kegg_met_allids = subset(allids, pathwaySource == "kegg" & grepl(rampId, pattern ="RAMP_C"))

kegg_identifier = read.csv("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/human/Kegg_pathway_identifier/kegg_classifier.csv")

####### Fisher exact test
for(ind in long_file){
  i = which(long_file == ind)
  data = readRDS(paste0(src_path,"/",ind))
  data_r= data[!duplicated(data$accession),]
  # only operate once
 data_r = data_r %>% mutate(accession = paste("hmdb:",accession,sep="")) %>%
  mutate(cas_registry_number = paste("CAS:",cas_registry_number,sep="")) %>%
  mutate(chebi_id = paste("chebi:",chebi_id,sep="")) %>%
  mutate(chemspider_id = paste("chemspider:",chemspider_id,sep=""))
  # Create a sample search
  search= unique(rbind(data.frame(analytes = data_r$accession),
                       data.frame(analytes =subset(data_r$cas_registry_number,nchar(data_r$cas_registry_number)>=5)),
                       data.frame(analytes =subset(data_r$chebi_id,nchar(data_r$chebi_id)>=7)),
                       data.frame(analytes =subset(data_r$chemspider_id,nchar(data_r$chemspider_id)>=12))))
  fisher.results <- RaMP:::runCombinedFisherTest(search, NameOrIds = "ids", total_genes = 20000, 
                                                 MCall = F, alternative = "less", min_path_size = 0, 
                                                 max_path_size = 150000, background_type = "database", 
                                                 background = "database", pathway_definitions = "RaMP")
  #filtered.fisher.results <- FilterFishersResults(fisher.results, pval_type = 'fdr', pval_cutoff=0.05)
  filtered.fisher.results = fisher.results[[1]][which(fisher.results[[1]]$pathwaySource == "kegg"),] %>%
    mutate(id_short = sub("map","",pathwayId) ) %>%
    mutate(  `kegg classifier` = unlist(lapply(id_short, function(x){
      temp = kegg_identifier[which(grepl(pattern = x, kegg_identifier$id)),]$group
      if(length(temp)!=0){
        return(temp) 
      }else{
        temp = "Deleted pathways from Kegg"
      }
    }
    )))%>%
    relocate(`kegg classifier`)
  
  # recalculate the significance
  
  # clusters <- RaMP::findCluster(filtered.fisher.results,
  #                               perc_analyte_overlap = 0.3,
  #                               min_pathway_tocluster = 2, perc_pathway_overlap = 0.2
  # )
  #results = clusters$fishresults %>% mutate_if(is.numeric, ~ round(., 8))
  results = filtered.fisher.results %>% mutate_if(is.numeric, ~ round(., 8))
  
  ########### append our detected metabolites
  pathwaydf <- getPathwayFromAnalyte(search, includeRaMPids = TRUE, 
                                     NameOrIds = "ids", find_synonym = FALSE)
  filtered_df = pathwaydf[which(pathwaydf$pathwayId %in%  results$pathwayId), ]
  
  # Recalculated p-val
  
  pval =c()
  for(j in 1:nrow(results)){
    total_in_pathway = results$Total_In_Path[j]
    in_data_in_pathway = results$Num_In_Path[j]
    not_in_data_in_pathway = total_in_pathway -  in_data_in_pathway
    in_data_outside_pathway = length(unique(filtered_df$rampId)) -  in_data_in_pathway
    outside_both= length(which(grepl(pattern = "RAMP_C",unique(allids[which(allids$pathwayRampId %in% unique(filtered_df$pathwayRampId)),]$rampId)))) - total_in_pathway - in_data_outside_pathway
    conti_table = data.frame(
      "in_pathway" = c(in_data_in_pathway,not_in_data_in_pathway ),
      "not_in_pathway" = c(in_data_outside_pathway, outside_both ),
      row.names = c("Detected metabolites", "Not detected metabolites"),
      stringsAsFactors = FALSE
    )
    fisher = fisher.test(conti_table, alternative = "greater")
    pval[j] = fisher$p.value
  }
  
  results_final = results %>% 
    mutate(Pval = pval) %>% 
    mutate(Pval_FDR = p.adjust(pval, method = "fdr"))%>% 
    mutate(Pval_Holm = p.adjust(pval, method = "holm")) %>%
    mutate(`Detected versus pathway total ratio` =Num_In_Path/Total_In_Path )%>%
    dplyr::select(-c("id_short","analytes","pathwaySource"))%>%
    rename("kegg_pathwayname"="pathwayName" )%>%
    relocate(`Detected versus pathway total ratio`)%>%
    relocate(`kegg classifier`) %>%
    arrange(Pval)
  
############################
name = c()
  for(j in results_final$pathwayId){
    commonname = sub("*;.*","",unique(filtered_df[which(filtered_df$pathwayId==j),]$commonName))
    name = c(name,paste(commonname, collapse = ";\n"))
  }
  setwd("~/paper/human_PATHWAYS")
  #Matrix name
  matrix_name = c("9AA Sublimation-(70-400)",
                            "9AA Sublimation-(400-1000)",
                            "CHCA sublimation (2step)+(70-400)",
                            "CHCA sublimation (2step)+(400-1000)")
  
  results_f = cbind(results_final, Detected_metabolites = name)
  write.csv(results_f, file= paste0(  matrix_name[i],"_ORA_enrichment_results_kegg_version.csv"))
  results_f_s = results_f %>% dplyr::select(-Detected_metabolites)
  write.csv(results_f_s, file= paste0(  matrix_name[i],"_ORA_enrichment_results_kegg_no_metabolites_name_version.csv"))
}

############################
setwd("~/paper/human_PATHWAYS")
temp = naturalsort::naturalsort(list.files(pattern="*name_version.csv"))
myfiles = lapply(temp, read.csv)
myfiles = lapply(myfiles, function(x){
  x = x[,1:10]
  return(x)
}
)
# Make a data.frame to store graphing stuff
matrixId =  c("9AA Sublimation-(70-400)",
                            "9AA Sublimation-(400-1000)",
                            "CHCA sublimation (2step)+(70-400)",
                            "CHCA sublimation (2step)+(400-1000)")
plotdf = data.frame()
for(i in 1:length(myfiles)){
  tempdf = cbind("Pathways" = myfiles[[i]]$kegg_pathwayname,
                 "Matrix" = rep(matrixId[i],length(myfiles[[i]]$kegg_pathwayname)),
                 "pval" = myfiles[[i]]$Pval,
                 "fdr_pval" = myfiles[[i]]$Pval_FDR,
                 "holm_pval" = myfiles[[i]]$Pval_Holm,
                 "id" = myfiles[[i]]$pathwayId,
                 "Classifier" = myfiles[[i]]$kegg.classifier,
                 "ratio" = myfiles[[i]]$Detected.versus.pathway.total.ratio
                 )
  plotdf = rbind(plotdf,tempdf)
}
################################################################################
View(plotdf)
plotdf[which(plotdf$Pathways == "Androgen and Estrogen Metabolism"),]$Classifier = "5.2 Endocrine system"
plotdf[which(plotdf$Pathways == "Steroidogenesis"),]$Classifier = "5.2 Endocrine system"
plotdf[which(plotdf$Pathways == "D-Arginine and D-Ornithine Metabolism"),]$Classifier = "1.6 Metabolism of other amino acids"

plotdf[which(plotdf$Pathways == "Ketone Body Metabolism"),]$Classifier = "1.3 Lipid metabolism"
#
#plotdf = plotdf[-which(plotdf$Classifier == "Deleted pathways from Kegg"),]



############
# ggplot(data=plotdf, aes(Matrix, Pathways,colour = FDR_pval)) + geom_point()
# dev.off()
# library(ggplot2)
# 
# plotdf$Cluster = sapply(plotdf$Pathways,function(x){ 
#                  temp = clusters[["fishresults"]][["cluster_assignment"]][which(clusters[["fishresults"]][["pathwayName"]]%in%x)]
#                  return(temp)
#                  })
## Small molecule tissue 2
# pathway_df =  plotdf
# pathway_df[which(pathway_df$Cluster == "6, 11"),]$Cluster = 6
# pathway_df[which(pathway_df$Cluster == "6, 12"),]$Cluster = 6
# pathway_df[which(pathway_df$Cluster == "5, 6"),]$Cluster = 5
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "Glycogen",ignore.case = T) 
#                  | grepl(pathway_df$Pathway,pattern = "Glu",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "cori",ignore.case = T)),]$Cluster = 2
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "nucleotide",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "purine",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "Methionine",ignore.case = T)),]$Cluster = 3
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "slc",ignore.case = T)),]$Cluster = 1
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "fatty acid",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "cholestoeol",ignore.case = T)),]$Cluster = 4
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "amino acid",ignore.case = T)),]$Cluster = 5
# 
# plotdf =pathway_df
# ####################### Setting colours
cols <- c("Carbohydrate metabolism"= '#0f7321',
          "Energy metabolism"='#f23a34',
          "Lipid metabolism"='#008080',
          "Nucleotide metabolism"='#0069b4',
          "Amino acid metabolism"='#00ffff',
          "Metabolism of other amino acids"='#ffa731',
          "Metabolism of cofactors and vitamins"='#fa2b73',
          "Biosynthesis of other secondary metabolites"= '#f072d4',
          "Endocrine system" = "#0fd214"
)
plotdf = plotdf %>% mutate(group =sub(" ","",sub(".*[0-9]","",sub(".*.[1-9]","",plotdf$Classifier))))%>%
mutate(significance = ifelse(as.numeric(pval)<=0.1, "Significant at 10% significance level",
                                        "Not statistically significant"))
cols = unlist(cols)
cols <- data.frame(color = unlist(cols),
                   group = names(unlist(cols)))

plotdf <- merge(plotdf, cols, by = "group", all.x = TRUE)
plotdf$Pathways_colour <- paste0("<span style=\"color: ",plotdf$color, "\">",plotdf$Pathways, "</span>")

plotdf = plotdf[!duplicated(plotdf[,2:3]),]

# Get most significant pathways
n = 50
filtered_df = data.frame()
for(i in 1:length(unique(plotdf$Matrix))){
  temp = plotdf[which(plotdf$Matrix == unique(plotdf$Matrix)[i]),]
  if(nrow(temp)>=n){
    temp = temp[order(temp$pval, decreasing = FALSE),][1:10,]
  }else{
    temp = temp[order(temp$pval, decreasing = FALSE),][1:nrow(temp),]
  }
  if( i == 1){
    filtered_df = temp
  }else{
    filtered_df = rbind(filtered_df, temp) 
  }
}
##############################

temp = ggplot(data=na.omit(plotdf), aes(x = factor(Matrix, level = c("9AA Sublimation-(70-400)",
                            "9AA Sublimation-(400-1000)",
                            "CHCA sublimation (2step)+(70-400)",
                            "CHCA sublimation (2step)+(400-1000)")), y = Pathways_colour, fill = group))+ 
       geom_point(aes(colour = as.numeric(pval),size = as.numeric(ratio)))+
  scale_colour_distiller(name="P value" 
                         ,palette = 'BuGn',
                         limits = c(0, 1), breaks = seq(0,1,0.2),
                         direction= -1)+
  scale_size_continuous(name = "Ratio of detected metabolites")+
  new_scale_colour() +
       geom_point(shape=1,aes(colour = significance,size =as.numeric(ratio) ))+
  scale_color_manual(values = c("Significant at 10% significance level" = "red",
                                "Not statistically significant" = "black"))+
   labs(
         title = "Comparason of pathways between different matrices",
         y = "Pathways", x = "Matrices molecule/polarity")+
       theme(title =element_text(size=15, face='bold'),
         axis.text.x = element_text(size = 12,
                                  angle =90,
                                  vjust = 0.5, hjust=1,
                                  colour = c(
                                             "9AA Sublimation-(70-400)"="#007AB6",
                            "9AA Sublimation-(400-1000)"="#007AB6",
                            "CHCA sublimation (2step)+(70-400)"="#5AC096",
                            "CHCA sublimation (2step)+(400-1000)"="#5AC096"
                                    )),#20
            axis.title = element_text(size = 9),#40
            axis.text.y = element_markdown(size = 9),
            legend.key.size = unit(1, 'cm'),
            legend.title = element_text(size=9),
            legend.text = element_text(size=9))+
  new_scale_colour() + theme(panel.background = element_rect(fill = "white"),
                                               panel.grid = element_line(color = "grey")) +
  geom_tile(aes(fill = group), colour = "white",
            width= 0 ,
            height = 0) + 
  scale_fill_manual(values  = c("Carbohydrate metabolism"= '#0f7321',
          "Energy metabolism"='#f23a34',
          "Lipid metabolism"='#008080',
          "Nucleotide metabolism"='#0069b4',
          "Amino acid metabolism"='#00ffff',
          "Metabolism of other amino acids"='#ffa731',
          "Metabolism of cofactors and vitamins"='#fa2b73',
          "Biosynthesis of other secondary metabolites"= '#f072d4',
          "Endocrine system" = "#0fd214"),
  drop = F,
  name = 'the kegg classifier')
  
# save image
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure5")
ggsave(filename = "Figure5B_modified.svg",
       plot = temp,
       width=10, height=14)
```

```{r 4Dplot}
plot_9aa = read.csv("~/paper/human_PATHWAYS/9AA Sublimation-(400-1000)_ORA_enrichment_results_kegg_version.csv")
plot_chca = read.csv("~/paper/human_PATHWAYS/CHCA sublimation (2step)+(400-1000)_ORA_enrichment_results_kegg_version.csv")
plot_chca$Detected_metabolites[7]
plot_9aa$Detected_metabolites[1]

setwd("~/paper/human_PATHWAYS")
# data = 9AA sm, data2 = CHCA2 sm
data = readRDS(paste0(src_path,"/",long_file[2])) %>% mutate(accession = paste("hmdb:",accession,sep="")) %>%
  mutate(cas_registry_number = paste("CAS:",cas_registry_number,sep="")) %>%
  mutate(chebi_id = paste("chebi:",chebi_id,sep="")) %>%
  mutate(chemspider_id = paste("chemspider:",chemspider_id,sep=""))
  # Create a sample search
search_9aa= unique(rbind(data.frame(analytes = data$accession),
                       data.frame(analytes =subset(data$cas_registry_number,nchar(data$cas_registry_number)>=5)),
                       data.frame(analytes =subset(data$chebi_id,nchar(data$chebi_id)>=7)),
                       data.frame(analytes =subset(data$chemspider_id,nchar(data$chemspider_id)>=12))))
# CHCA2 sm
data2 = readRDS(paste0(src_path,"/",long_file[4]))%>% mutate(accession = paste("hmdb:",accession,sep="")) %>%
  mutate(cas_registry_number = paste("CAS:",cas_registry_number,sep="")) %>%
  mutate(chebi_id = paste("chebi:",chebi_id,sep="")) %>%
  mutate(chemspider_id = paste("chemspider:",chemspider_id,sep=""))

data2[which(grepl(data2$name,pattern = "Arginine",ignore.case = T)),]$name
data[which(grepl(data$name,pattern = "Arginine",ignore.case = T)),]$name

  # Create a sample search
search_chca= unique(rbind(data.frame(analytes = data2$accession),
                       data.frame(analytes =subset(data2$cas_registry_number,nchar(data2$cas_registry_number)>=5)),
                       data.frame(analytes =subset(data2$chebi_id,nchar(data2$chebi_id)>=7)),
                       data.frame(analytes =subset(data2$chemspider_id,nchar(data2$chemspider_id)>=12))))
# Get the result of pathway analysis
pathwayname = "thiamine"
potential_9aa = getPathwayFromAnalyte(search_9aa,includeRaMPids = T) %>% filter(grepl(pathwayName,pattern = pathwayname,ignore.case = T))%>%filter(!duplicated(rampId))
potential_chca = getPathwayFromAnalyte(search_chca,includeRaMPids = T) %>% filter(grepl(pathwayName,pattern = pathwayname,ignore.case = T))%>%filter(!duplicated(rampId))


list_of_moi_chca = potential_chca$inputId
# list_of_moi_9aa = c("CAS:18191-20-3",
#                 "CAS:56-85-9" ,
#                 "CAS:643-13-0",
#                 "CAS:584-85-0")


#
CHCA2_alanine_metabolism_metabolites = data2[which(data2$cas_registry_number %in% list_of_moi_chca),]$exp_mz
#AA_alanine_metabolism_metabolites = data[which(data$cas_registry_number %in% list_of_moi_chca),]$exp_mz
AA_alanine_metabolism_metabolites = data[which(data$cas_registry_number %in% list_of_moi_chca),]$exp_mz
  
savepath = "~/metabolomic/figure5"

# Funtion convert 0 to nA
any_column_NA <- function(x){
    any(x == 0)
}
replace_NA_0 <- function(x){
    if_else(x==0,NA,x)
}
# Plot list
chca_plot_matrix = list()
for(mz in CHCA2_alanine_metabolism_metabolites){
  base = floor((mz-400)/15)*15+400
  cardinaldata = readImzML(paste0("CHCA_2step_+_400to1000ranged_from_",base,base+15),
                           folder = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output/CHCA2_400_1000_entire_tissue")
  temp = image(cardinaldata,mz =mz)
  plot_matrix =log1p(mirror.matrix((temp[["facets"]][[1]][[1]][["values"]])))
  colnames(plot_matrix) = c(1:ncol(plot_matrix))
  
  chca_plot_matrix[[paste0(mz)]] = setNames(melt(plot_matrix), c('rows', 'cols', 'values')) %>% mutate_if(any_column_NA,replace_NA_0 )
}

aa_plot_matrix = list()
for(mz in AA_alanine_metabolism_metabolites){
  base = floor((mz-400)/15)*15+400
  cardinaldata = readImzML(paste0("9AA_-_400to1000ranged_from_",base,base+15),
                           folder = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output/9AA_400_1000_entire_tissue")
  temp = image(cardinaldata,mz =mz)
  plot_matrix =log1p(mirror.matrix((temp[["facets"]][[1]][[1]][["values"]])))
  colnames(plot_matrix) = c(1:ncol(plot_matrix))
  aa_plot_matrix[[paste0(mz)]] = setNames(melt(plot_matrix), c('rows', 'cols', 'values')) %>% mutate_if(any_column_NA,replace_NA_0 )
}
##############plot
library(rgl)
save <- getOption("rgl.useNULL")
options(rgl.useNULL=TRUE)

colours = c("red",
            "red",
            "red",
            "green",
            "blue",
            "blue",
            "purple",
  "purple")
avg_intensity = mean(na.omit(chca_plot_matrix[[1]][,3])) 
plot3d(chca_plot_matrix[[1]], col = c(rep("red",times = nrow(chca_plot_matrix[[1]]))))

i=2
save <- getOption("rgl.useNULL")
options(rgl.useNULL=TRUE)
axes3d()
plot3d(x = chca_plot_matrix[[i]][,1], z = chca_plot_matrix[[i]][,2],y = chca_plot_matrix[[i]][,3], col = c(rep("purple",times = nrow(chca_plot_matrix[[i]]))),alpha = 1,
       xlab = '', zlab = '', ylab = 'Intensity',screen = list(z = -30, x = -60))
avg_intensity = log1p(mean(exp(na.omit(chca_plot_matrix[[i]][,3]))-1))
avg_intensity
planes3d(0,1,0,-avg_intensity,col = 'yellow', alpha = 0.3)
view3d(phi=40, theta = 0,fov = 180,zoom = 0.7,type = "modelviewpoint")
widget <- rglwidget()
if (interactive())
  widget
length(na.omit(chca_plot_matrix[[i]][,3]))/length(which(imagelength_chca!=0))
###################
read.bmp = readRDS("~/paper/programs/read_bmp.RDS")
bmp_9aa_lipid = read.bmp("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/raw/ImzML_expand/9AA/AREA01_slide2_TissueB_Negative_400to1000_profile.bmp")

library(imager)
library("EBImage")
bmp_9aa_lipid_gs =  (0.2126*bmp_9aa_lipid[,,1]  + 0.7152*bmp_9aa_lipid[,,2]  + 0.0722*bmp_9aa_lipid[,,3])/255
imagelength = apply(bmp_9aa_lipid_gs, 2, function(x){ifelse(x>=quantile(bmp_9aa_lipid_gs)[2]+0.1,1,0)}) 
imagelength = EBImage::resize(imagelength,w = 716, h = 1010)
image(imagelength)
dev.off()
length(which(imagelength!=0))

bmp_CHCA_lipid = read.bmp("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/raw/ImzML_expand/CHCA_2step/AREA01_ATO-1_TissueB_POS_400to1000_profile.bmp")

bmp_CHCA_lipid_lipid_gs =  (0.2126*bmp_CHCA_lipid[,,1]  + 0.7152*bmp_CHCA_lipid[,,2]  + 0.0722*bmp_CHCA_lipid[,,3])/255
imagelength_chca = apply(bmp_CHCA_lipid_lipid_gs , 2, function(x){ifelse(x>=quantile(bmp_CHCA_lipid_lipid_gs )[2]+0.1,1,0)}) 
imagelength_chca = EBImage::resize(imagelength_chca,w = 675, h = 970)
image(imagelength_chca)
dev.off()
length(which(imagelength_chca!=0))


###########
i=2
save <- getOption("rgl.useNULL")
options(rgl.useNULL=TRUE)
axes3d()
plot3d(x = aa_plot_matrix[[i]][,1], z = aa_plot_matrix[[i]][,2],y = aa_plot_matrix[[i]][,3], col = c(rep("purple",times = nrow(aa_plot_matrix[[i]]))),alpha = 1,
       xlab = '', zlab = '', ylab = 'Intensity',screen = list(z = -30, x = -60))
avg_intensity = log1p(mean(exp(na.omit(aa_plot_matrix[[i]][,3]))-1))
avg_intensity
planes3d(0,1,0,-avg_intensity,col = 'yellow', alpha = 0.3)
view3d(phi=40, theta = 0,fov = 180,zoom = 0.6,type = "modelviewpoint")
widget <- rglwidget()
if (interactive())
  widget

length(na.omit(aa_plot_matrix[[i]][,3]))/length(which(imagelength!=0))
length(na.omit(chca_plot_matrix[[i]][,3]))/length(which(imagelength_chca!=0))
###################




for(i in 2:length(chca_plot_matrix)){
  plot3d(chca_plot_matrix[[i]], col = c(rep(colours[i],times = nrow(chca_plot_matrix[[i]]))), add = T)
}
# legend3d("topright", legend = c("N-Acetyl-D-Glucosamine 6-Phosphate",
#                                 "L-Glutamine",
#                                 "Fructose 6-phosphate",
#                                 "Anserine"), pch = 3, col = c("red",
#                                                                                  "green",
#                                                                                  "blue",
#                                                                                  "purple"), cex=1, inset=c(0.02))
widget <- rglwidget()
if (interactive())
  widget
setwd("~/metabolomic")
htmlwidgets::saveWidget(widget, "CHCA_.html")
close3d()


#9AA
save <- getOption("rgl.useNULL")
options(rgl.useNULL=TRUE)

colours = c("red",
            "green",
            "blue",
  "purple")
plot3d(aa_plot_matrix[[1]], col = c(rep("red",times = nrow(aa_plot_matrix[[1]]))))
aa_plot_matrix[[1]]

for(i in 2:length(aa_plot_matrix)){
  plot3d(aa_plot_matrix[[i]], col = c(rep(colours[i],times = nrow(aa_plot_matrix[[i]]))), add = T)
}
# legend3d("topright", legend = c("N-Acetyl-D-Glucosamine 6-Phosphate",
#                                 "L-Glutamine",
#                                 "Fructose 6-phosphate",
#                                 "Anserine"), pch = 3, col = c("red",
#                                                                                  "green",
#                                                                                  "blue",
#                                                                                  "purple"), cex=1, inset=c(0.02))
widget <- rglwidget()
if (interactive())
  widget
setwd("~/metabolomic")
htmlwidgets::saveWidget(widget, "9aa.html",selfcontained=T)
close3d()
rgl.dev()
```
```{pathwayplot}

###
#unique_id = unique(data$accession)


# create matrix_attri to help create upsetR plot
## nn = number of top expressed metabolites we want select
nn = length(unique_id)
matrix_attri = data.frame(matrix(0,nrow = nn, ncol =length(unique(data$matrix_polarity))))
colnames(matrix_attri) = unique(data$matrix_polarity)
for (i in 1:nn){
  #make a temprory matrixname stores the polar+matrix name with matched HMDB id
  matrixname = unique(data[which(data$mz_hmdb==unique_id[i]),]$matrix_polarity)
  #matrixname = unique(data[which(data$accession==unique_id[i]),]$matrix_polarity)
  for(j in 1:length(matrixname)){
    # for each row, if the matrix name is matched with colname of matrix_attri, then the slot has 1 
    matrix_attri[i,which(colnames(matrix_attri)==matrixname[j])]=1
  }
}
# plot upserR


a= upset(matrix_attri,
             colnames(matrix_attri),
             #mainbar.y.label = "Number of uniquely detected m/z peaks",
             group_by='degree',
             width_ratio=0.1,
         min_size = 40,
        sort_intersections_by = c('degree','cardinality'),
        matrix=(
        intersection_matrix(geom=geom_point(shape='circle filled', size=2))+ 
          scale_color_manual(
          values=c("9AA Sublimation-"="#007AB6",
                                                         "9AA Sublimation+" = "#ABC7E6",
                                                         "9AA Sublimation(2step)-"="#413975",
                                                         "9AA Sublimation(2step)+"= "#9068AC",
                                                         "DHB Sublimation-"="#F77800",
                                                         "DHB Sublimation+"="#FDB772",
                                                         "CHCA sublimation (2step)-"= "#2FA143",
                                                         "CHCA sublimation (2step)+"="#5AC096",
                                                         "CHCA sublimation-"="#916729",
                                                         "CHCA sublimation+"="#C3A128"),
          # values=c('9AA-'="#007AB6",
          #          '9AA+'="#ABC7E6",
          #          'CHCA(2step)+'="#5AC096",
          #          'CHCA(2step)-'="#2FA143"
          #          ),
          guide=guide_legend(override.aes=list(shape='circle'))
        )
      ),
      queries=list(
        upset_query(set='9AA Sublimation-', fill='#007AB6'),
        upset_query(set='9AA Sublimation+', fill='#ABC7E6'),
        upset_query(set='9AA Sublimation(2step)-', fill='#413975'),
        upset_query(set='9AA Sublimation(2step)+', fill='#9068AC'),
        upset_query(set='DHB Sublimation+', fill ='#FDB772'),
        upset_query(set='DHB Sublimation-', fill ='#F77800'),
        upset_query(set='CHCA sublimation (2step)+', fill ='#5AC096'),
        upset_query(set='CHCA sublimation (2step)-', fill ='#2FA143'),
        upset_query(set='CHCA sublimation+', fill ='#C3A128'),
        upset_query(set='CHCA sublimation-', fill ='#916729')
      ),

      #Lipid
      # queries=list(
      #   upset_query(set='9AA-', fill='#007AB6'),
      #   upset_query(set='9AA+', fill='#ABC7E6'),
      #   upset_query(set='CHCA(2step)+', fill ='#5AC096'),
      #   upset_query(set='CHCA(2step)-', fill ='#2FA143')
      # ),
      base_annotations=list(
        'Intersection size'=intersection_size(
          text_colors=c(
            on_background='brown', on_bar='green'
          ),
          text = list(
          size = 0,
          vjust = -2
          )
        )+ 
          annotate(
          geom='text', x=Inf, y=Inf,
          label=paste('Total:', nrow(matrix_attri)),
          vjust=1, hjust=1
        )+ 
          ylab('Intersection Size')+
          ggtitle('Unique matched m/z found in ROI of matrix/polarity intersections')+
          theme_bw()+ theme(
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
      ),
      themes=upset_modify_themes(
        list(
          'Intersection Size'=theme(text=element_text(
            size=13, angle = 90)),
          'overall_sizes'=theme(axis.text.x=element_text(angle=90))
        )
      )
    )

##############################################################

# ggsave(filename = "Overalp_between_matched_mz_generated_Tissue2.svg",
#        plot = a,
#        width=6*1.681, height=6)

setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(filename = "Figure2C.svg",
       plot = a,
       width=6*1.681, height=6)
```

```{r}
library(rgl)

save <- getOption("rgl.useNULL")
options(rgl.useNULL=TRUE)
x <- sort(rnorm(1500))
y <- rnorm(1500)
z1 <- rnorm(1500)
m = cbind(x,y,z1)
m2 = cbind(z1,y,x)


plot3d(m2, col = c(rep("yellow",times = 1500)))
plot3d(m, col = c(rep("blue",times = 1500)), add = T)
widget <- rglwidget()
if (interactive())
  widget

close3d()
imzml_9aa = readImzML("9AA_-_70to400ranged_from_140150",
                      folder = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output/9AA_40_400_entire_tissue")

image(imzml_9aa, mz =146.0229)


imzml_chca = readImzML("CHCA_2step_+_70to400ranged_from_140150",
                      folder = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output/CHCA2_70_400_entire_tissue")

image(imzml_chca, mz =148.0766)
```




