---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r env}
.libPaths("/stornext/Bioinf/data/lab_brain_cancer/users/t_lu/R/x86_64-pc-linux-gnu-library/4.2")
library(ggplot2)
library(ggpattern)
library(readxl)
library(RRHO2)
library(dplyr)
library(RaMP)
library(magick)
library(rsvg)
library(readxl)
library(viridis)
library(ComplexUpset)
library(Cairo)
library(MASS) 
library(reshape2)
library(ggnewscale)
library(transport)
library(magrittr)
library(seriation)
library(cowplot)
library(png)
library(naturalsort)
library(stringdist)
library(peRspective)
library(ggtext)
# Set ramp connection
pkg.globals <- setConnectionToRaMP(
  dbname = "ramp", username = "root", conpass = "ADMIN",
  host = "localhost",socket = "/stornext/Home/data/allstaff/l/lu.t/mysql/var/run/mysqld/mysql.sock")

# Set root directory
root_directory = "/stornext/Home/data/allstaff/l/lu.t/paper_final"

```

```{r figure3a}

# Set working directory
setwd(root_directory)
data = readRDS(paste0(root_directory, "/feature_files/lipids_annotated_list.RDS")) %>% mutate(matrix_polarity = paste0(matrix, polarity))

matrix_polarity = paste0(data$matrix, data$polarity)
#
if (length(grep(colnames(data), pattern = "matrix_polarity")) == 0) {
  data = cbind(data, matrix_polarity)
}
# num stores the number of unique detected small molecules, num_mz, number of unique m/z s
num = c()
num_mz = c()
src_path = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230303_lipids/Sarah_Best_Imaging_Lipids_MA-SB-436/output"
# peaks_file = naturalsort(list.files(src_path,
#                         pattern = "T_peaksum.RData"))
#
# for(i in peaks_file){
#   load(paste0(src_path,"/",i))
#   num_backgroundmz = c(num_backgroundmz, nrow(peaksum_b_df))
# }
#
for (i in 1:length(unique(matrix_polarity))) {
  num_mz[i] = length(unique(data[which(data$matrix_polarity == unique(matrix_polarity)[i]), ]$exp_mz))
  num[i] = length(unique(data[which(data$matrix_polarity == unique(matrix_polarity)[i]), ]$chemical_formula))
}
# barplot = store of the data
barplot = data.frame(cbind(c(num, num_mz),
                           mp = rep(unique(matrix_polarity), times = 2)),
                     label = c(
                       rep("Potential chemcial formulas matched", times = length(num)),
                       rep("Experimental m/z", times = length(num))
                     ))


b = ggplot(data = barplot, aes(
  x = factor(mp, level = c(
    "9AA-",
    "9AA+",
    "CHCA(2step)-",
    "CHCA(2step)+"
  )),
  y = as.integer(V1),
  fill = mp,
  pattern = label
)) +
  geom_bar_pattern(
    position = "dodge",
    stat = "identity",
    color = "black",
    pattern_fill = "black",
    pattern_angle = 45,
    pattern_density = 0.1,
    pattern_spacing = 0.025,
    pattern_key_scale_factor = 0.6
  ) +
  scale_fill_manual(
    values = c(
      "9AA-" = "#007AB6",
      "9AA+" = "#ABC7E6",
      "CHCA(2step)+" = "#5AC096",
      "CHCA(2step)-" = "#2FA143"
    ),
    guide = "none"
  ) +
  # scale_fill_manual(values = rep(c("#007AB6",
  #                                              "#ABC7E6",
  #                                              "#5AC096",
  #                                              "#2FA143"),each = 1), guide = "none")+
  scale_pattern_manual(values = c(
    `Experimental m/z` = "stripe",
    `Potential chemcial formulas matched` = "none"
  )) +
  labs(x = "Matrix/Polarity combinations", y = "Number of Detected Features", pattern = "Type of Feature") +
  guides(pattern = guide_legend(override.aes = list(fill = "white"))) +
  scale_x_discrete(guide = guide_axis(n.dodge = 1,
                                      angle = 45)) +
  theme_bw() + theme(
    axis.text.x = element_text(
      size = 7,
      colour = c(
        "9AA-" = "#007AB6",
        "9AA+" = "#ABC7E6",
        "CHCA(2step)+" = "#5AC096",
        "CHCA(2step)-" = "#2FA143"
      )
    ),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black")
  )
# Save image
ggsave(
  filename = "Figure3A.svg",
  plot = b,
  width = 6 * 1.681,
  height = 6
)

```

```{r figure2b}
########################
decimalplaces <- function(x) {
  if ((x %% 1) != 0) {
    nchar(strsplit(sub('0+$', '', as.character(x)), ".", fixed = TRUE)[[1]][[2]])
  } else {
    return(0)
  }
}

source_directory = paste0(root_directory, "/bulk_metabolomics")
lipid = "/Lipids_LCMS"
# Set working directory
setwd(source_directory)
# Get file namesF
lipidomics = data.frame(t(read_xlsx(
  path = paste0(
    source_directory,
    lipid,
    "/",
    list.files(paste0(source_directory, lipid),
               pattern = "Lipidomics.xlsx")
  ),
  na = "ND"
)))
##########
getOption(x = "digits")
current.n.dgt <- getOption("digits")
options(digits = 11)

lipidomics = lipidomics[, 1:5] %>% `colnames<-`(paste0(lipidomics[1, 1:5])) %>% dplyr::slice(-c(1, 2))
lipidomics = lipidomics %>% dplyr::mutate(Mass_numeric = as.numeric(Mass)) %>% dplyr::mutate(mz_pos_hydro = as.numeric(Mass) +
                                                                                               1.00727647) %>%
  dplyr::mutate(mz_neg_hydro = as.numeric(Mass) - 1.00727647) %>% dplyr::mutate(mz_pos_soldium = as.numeric(Mass) +
                                                                                  22.989769) %>% dplyr::mutate(mz_pos_potassium = as.numeric(Mass) + 39.0983)
##########
lipid_test = lipidomics
########################
getfoldchange = function(brain, tumour, background) {
  a = brain
  b = tumour
  normaliseda = log1p((a - background) * sum(b - background) / sum(a - background))
  normalisedb = log1p((b - background))
  temp = normalisedb - normaliseda
  return(temp)
}
lipid_test = lipid_test  %>% mutate(brain = as.numeric(SB_PLCER_01)) %>% mutate(tumour = as.numeric(SB_PLCER_02)) %>% mutate(background = as.numeric(`SB_PLCER_EB (blank)`)) %>% dplyr::select(-c(1:3))
lipid_test = lipid_test %>% mutate(logFC = getfoldchange(brain, tumour, background)) %>% na.omit()
View(lipid_test)
############################
length_matched = c()
detail_matched = list()
for (i in 1:4) {
  mass_accuracy = 10 * 1e-6
  sub_data = data[which(data$matrix_polarity == unique(matrix_polarity)[i]), ]
  exp_mz = unique(sub_data$exp_mz)
  
  if (grepl(unique(matrix_polarity)[i],
            pattern = "+",
            fixed = TRUE) == TRUE) {
    potential_match_hydro = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[4]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    ########
    potential_match_pota = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[7]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    ########
    potential_match_sodium = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[6]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    
    detail_matched[[i]] = data.frame(
      matched_lipid_name = c(
        names(potential_match_hydro),
        names(potential_match_pota),
        names(potential_match_sodium)
      ),
      experimental_mz = c(
        potential_match_hydro,
        potential_match_pota ,
        potential_match_sodium
      ),
      adduct_ion = c(
        rep("[M+H]+", times = length(potential_match_hydro)),
        rep("[M+K]+", times = length(potential_match_pota)),
        rep("[M+Na]+", times = length(potential_match_sodium))
      )
    )
    
    length_matched = c(length_matched,
                       length(unique(names(
                         na.omit(potential_match_hydro)
                       ))) + length(unique(names(
                         na.omit(potential_match_sodium)
                       ))) + length(unique(names(
                         na.omit(potential_match_pota)
                       ))))
  } else{
    potential_match_neg = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[5]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    detail_matched[[i]] = data.frame(
      matched_lipid_name = c(names(potential_match_neg)),
      experimental_mz = potential_match_neg,
      adduct_ion = c(rep(
        "[M-H]-", times = length(potential_match_neg)
      ))
    )
    length_matched = c(length_matched, length(unique(names(
      na.omit(potential_match_neg)
    ))))
  }
}
names(length_matched) = unique(matrix_polarity)
length_matched
##############################################
for (i in 1:4) {
  matched_df = detail_matched[[i]] %>% mutate(full_name = sub(".*[.]", "", matched_lipid_name)) %>% mutate(short_name = sub("[.].*", "", matched_lipid_name))
  theory_mz = unlist(apply(
    matched_df,
    MARGIN = 1 ,
    FUN = function(x) {
      if (x[3] == "[M+H]+") {
        temp =  as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_pos_hydro)
      } else if (x[3] == "[M+K]+") {
        temp =  as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_pos_potassium)
      } else if (x[3] == "[M+Na]+") {
        temp =  as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_pos_soldium)
      } else{
        temp = as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_neg_hydro)
      }
      return(temp)
    }
  ))
  molecular_mass = unlist(apply(
    matched_df,
    MARGIN = 1 ,
    FUN = function(x) {
      temp = as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$Mass)
      return(temp)
    }
  ))
  matched_df = data.frame(cbind(matched_df, theory_mz, molecular_mass)) %>% dplyr::select(c(-1))
  detail_matched[[i]]  = matched_df
  length_matched[i] = length(unique(matched_df$short_name))
  ##
  # Set working directory
  setwd(paste0(root_directory, "/bulk_metabolomics/Lipids_LCMS"))
  write.csv(matched_df, paste0(unique(matrix_polarity)[i], "matched_lipids_10ppm.csv"))
}




plot_df = data.frame()
for (i in 1:4) {
  sub_data = data[which(data$matrix_polarity == unique(matrix_polarity)[i]), ]
  logFC = unlist(apply(
    detail_matched[[i]],
    MARGIN = 1 ,
    FUN = function(x) {
      short_name = x[4]
      ####################
      lcms_fc = as.numeric(lipid_test[which(rownames(lipid_test) == as.character(short_name)), ]$logFC)
      ###################
      ims_fc_list = as.numeric(sub_data[which(round(sub_data$exp_mz, digits = 8) ==
                                                paste0(round(as.numeric(x[1]), digits = 8))), ]$diff_mean)
      ims_fc = ims_fc_list[which.min(abs(ims_fc_list - lcms_fc))]
      #return(ims_fc)
      return(ims_fc)
    }
  ))
  ###################
  temp_df = data.frame(
    names = detail_matched[[i]]$short_name,
    matrix = rep(unique(matrix_polarity)[i], times = nrow(detail_matched[[i]])),
    logFC = logFC
  )
  plot_df = rbind(plot_df, temp_df)
}
lcms_df = data.frame(
  names = rownames(lipid_test),
  matrix = rep("LCMS", times = nrow(lipid_test)),
  logFC = lipid_test$logFC
)

final_plot_df = rbind(plot_df, lcms_df)
########################
final_final_plot_df = data.frame()
for (i in unique(final_plot_df$names)) {
  lcms_sub = final_plot_df[which(final_plot_df$names == i &
                                   final_plot_df$matrix == "LCMS"), ]
  for (j in unique(matrix_polarity)) {
    sublist = final_plot_df[which(final_plot_df$names == i &
                                    final_plot_df$matrix == j), ]
    index = which.min(abs(as.numeric(sublist$logFC) - as.numeric(lcms_sub$logFC)))
    final_final_plot_df = rbind(final_final_plot_df, sublist[index, ])
  }
  final_final_plot_df = rbind(final_final_plot_df, lcms_sub)
}
#########################
saveRDS(final_final_plot_df, file = "10ppm_lipid_matched_plotdf.rds")





######################### 2ppm
length_matched = c()
detail_matched = list()
for (i in 1:4) {
  mass_accuracy = 2*1e-6
  sub_data = data[which(data$matrix_polarity == unique(matrix_polarity)[i]), ]
  exp_mz = unique(sub_data$exp_mz)
  
  if (grepl(unique(matrix_polarity)[i],
            pattern = "+",
            fixed = TRUE) == TRUE) {
    potential_match_hydro = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[4]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    ########
    potential_match_pota = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[7]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    ########
    potential_match_sodium = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[6]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    
    detail_matched[[i]] = data.frame(
      matched_lipid_name = c(
        names(potential_match_hydro),
        names(potential_match_pota),
        names(potential_match_sodium)
      ),
      experimental_mz = c(
        potential_match_hydro,
        potential_match_pota ,
        potential_match_sodium
      ),
      adduct_ion = c(
        rep("[M+H]+", times = length(potential_match_hydro)),
        rep("[M+K]+", times = length(potential_match_pota)),
        rep("[M+Na]+", times = length(potential_match_sodium))
      )
    )
    
    length_matched = c(length_matched,
                       length(unique(names(
                         na.omit(potential_match_hydro)
                       ))) + length(unique(names(
                         na.omit(potential_match_sodium)
                       ))) + length(unique(names(
                         na.omit(potential_match_pota)
                       ))))
  } else{
    potential_match_neg = unlist(apply(
      lipid_test,
      MARGIN = 1,
      FUN = function(x) {
        num = x[5]
        temp = unlist(lapply(exp_mz, function(y) {
          if ((
            abs(as.numeric(y) - as.numeric(num)) / as.numeric(num) <= as.numeric(mass_accuracy)
          )) {
            temp2 = as.numeric(y)
            returntemp = temp2[which.min(temp2 - as.numeric(num))]
            names(returntemp) =  sub("Name", "", as.character(x[1]))
            return(returntemp)
          } else{
            return(NULL)
          }
        }))
        return(temp)
      }
    ))
    detail_matched[[i]] = data.frame(
      matched_lipid_name = c(names(potential_match_neg)),
      experimental_mz = potential_match_neg,
      adduct_ion = c(rep(
        "[M-H]-", times = length(potential_match_neg)
      ))
    )
    length_matched = c(length_matched, length(unique(names(
      na.omit(potential_match_neg)
    ))))
  }
}
names(length_matched) = unique(matrix_polarity)
length_matched
##############################################
for (i in 1:4) {
  matched_df = detail_matched[[i]] %>% mutate(full_name = sub(".*[.]", "", matched_lipid_name)) %>% mutate(short_name = sub("[.].*", "", matched_lipid_name))
  theory_mz = unlist(apply(
    matched_df,
    MARGIN = 1 ,
    FUN = function(x) {
      if (x[3] == "[M+H]+") {
        temp =  as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_pos_hydro)
      } else if (x[3] == "[M+K]+") {
        temp =  as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_pos_potassium)
      } else if (x[3] == "[M+Na]+") {
        temp =  as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_pos_soldium)
      } else{
        temp = as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$mz_neg_hydro)
      }
      return(temp)
    }
  ))
  molecular_mass = unlist(apply(
    matched_df,
    MARGIN = 1 ,
    FUN = function(x) {
      temp = as.numeric(lipid_test[which(lipid_test$Name == x[4]), ]$Mass)
      return(temp)
    }
  ))
  matched_df = data.frame(cbind(matched_df, theory_mz, molecular_mass)) %>% dplyr::select(c(-1))
  detail_matched[[i]]  = matched_df
  length_matched[i] = length(unique(matched_df$short_name))
  ##
  # Set working directory
  setwd(paste0(root_directory, "/bulk_metabolomics/Lipids_LCMS"))
  write.csv(matched_df, paste0(unique(matrix_polarity)[i], "matched_lipids_2ppm.csv"))
}
########################
decimalplaces <- function(x) {
  if ((x %% 1) != 0) {
    nchar(strsplit(sub('0+$', '', as.character(x)), ".", fixed = TRUE)[[1]][[2]])
  } else {
    return(0)
  }
}


plot_df = data.frame()
for (i in 1:4) {
  sub_data = data[which(data$matrix_polarity == unique(matrix_polarity)[i]), ]
  logFC = unlist(apply(
    detail_matched[[i]],
    MARGIN = 1 ,
    FUN = function(x) {
      short_name = x[4]
      ####################
      lcms_fc = as.numeric(lipid_test[which(rownames(lipid_test) == as.character(short_name)), ]$logFC)
      ###################
      ims_fc_list = as.numeric(sub_data[which(round(sub_data$exp_mz, digits = 8) ==
                                                paste0(round(as.numeric(x[1]), digits = 8))), ]$diff_mean)
      ims_fc = ims_fc_list[which.min(abs(ims_fc_list - lcms_fc))]
      #return(ims_fc)
      return(ims_fc)
    }
  ))
  ###################
  temp_df = data.frame(
    names = detail_matched[[i]]$short_name,
    matrix = rep(unique(matrix_polarity)[i], times = nrow(detail_matched[[i]])),
    logFC = logFC
  )
  plot_df = rbind(plot_df, temp_df)
}
lcms_df = data.frame(
  names = rownames(lipid_test),
  matrix = rep("LCMS", times = nrow(lipid_test)),
  logFC = lipid_test$logFC
)

final_plot_df = rbind(plot_df, lcms_df)
########################
final_final_plot_df = data.frame()
for (i in unique(final_plot_df$names)) {
  lcms_sub = final_plot_df[which(final_plot_df$names == i &
                                   final_plot_df$matrix == "LCMS"), ]
  for (j in unique(matrix_polarity)) {
    sublist = final_plot_df[which(final_plot_df$names == i &
                                    final_plot_df$matrix == j), ]
    index = which.min(abs(as.numeric(sublist$logFC) - as.numeric(lcms_sub$logFC)))
    final_final_plot_df = rbind(final_final_plot_df, sublist[index, ])
  }
  final_final_plot_df = rbind(final_final_plot_df, lcms_sub)
}
saveRDS(final_final_plot_df, file = "2ppm_lipid_matched_plotdf.rds")

########## Analysis

ppm_10 = readRDS("~/paper/programs/10ppm_lipid_matched_plotdf.rds") %>% mutate(label = "10 ppm")
ppm_2 = readRDS("~/paper/programs/2ppm_lipid_matched_plotdf.rds") %>% mutate(label = "2 ppm")

plotdf_combined = rbind(ppm_10, ppm_2) %>% filter(matrix != "LCMS")

######
length_lcms = length(which(ppm_2$matrix == "LCMS"))
# plot
temp = ggplot(data = plotdf_combined, aes(
  x = factor(matrix, level = c(
    "9AA-",
    "9AA+",
    "CHCA(2step)-",
    "CHCA(2step)+"
  )),
  fill = matrix,
  pattern = label
)) +
  geom_bar_pattern(
    position = "dodge",
    stat = "count",
    color = "black",
    pattern_fill = "black",
    pattern_angle = 45,
    pattern_density = 0.1,
    pattern_spacing = 0.025,
    pattern_key_scale_factor = 0.6
  ) +
  scale_fill_manual(
    values = c(
      "9AA-" = "#007AB6",
      "9AA+" = "#ABC7E6",
      "CHCA(2step)+" = "#5AC096",
      "CHCA(2step)-" = "#2FA143"
    ),
    guide = "none"
  ) +
  scale_y_continuous(
    labels = function(x)
      paste0(round(x * 100 / length_lcms, digits = 1) , "%")
  ) +
  # scale_fill_manual(values = rep(c("#007AB6",
  #                                              "#ABC7E6",
  #                                              "#5AC096",
  #                                              "#2FA143"),each = 1), guide = "none")+
  scale_pattern_manual(values = c(`10 ppm` = "stripe",
                                  `2 ppm` = "none")) +
  labs(x = "Matrix/Polarity combinations", y = "Percentage of overlapping m/z peaks", pattern = "Mass accuracy used for aligning") +
  guides(pattern = guide_legend(override.aes = list(fill = "white"))) +
  theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank())

ggsave(
  filename = "Figure3B.svg",
  plot = temp,
  width = 6 * 1.681,
  height = 6
)
#########################
convert_value  = function(x, range) {
  x = as.numeric(na.omit(x))
  range = as.numeric(na.omit(range))
  ##
  if (length(unique(sign(x))) == 1) {
    ratio = (max(x) - min(x)) / (max(range) - min(range))
    newx = (x - min(x)) / ratio + min(range)
    return(newx)
  } else{
    pos_range = c(0, max(x))
    neg_range = c(min(x), 0)
    newx = as.numeric(unlist(lapply(x, function(y) {
      if (y >= 0) {
        temp_ratio = max(x) / max(range)
        new_y = (y - 0) / temp_ratio
        return(new_y)
      } else{
        temp_ratio = min(x) / min(range)
        new_y = (y - 0) / temp_ratio
        return(new_y)
      }
    })))
    return(newx)
  }
}
# ppm_10_scaled = data.frame()
# for(i in unique(ppm_10$matrix)){
#   temp = ppm_10[which(ppm_10$matrix ==i),]
#   temp$logFC = convert_value(temp$logFC,c(-1,1))
#   ppm_10_scaled =rbind(ppm_10_scaled,temp)
# }
ppm_10 = ppm_10 %>% mutate(status = ifelse(logFC >= 0, "Upregulated", "Downregulated")) %>% mutate(panel = ifelse(
  names %in% naturalsort::naturalsort(unique(ppm_10$names))[1:78],
  "Panel1",
  "Panel2"
))

temp2 = ggplot(data = ppm_10, aes(
  x = matrix,
  y = names,
  fill = logFC + ifelse(logFC > 0, 0.5, -0.5)
)) + geom_tile() +
  scale_fill_gradient2(high = "red",
                       low = "blue",
                       name = "log1pFC") + scale_size(range = c(1, 2)) + theme_bw() + facet_wrap( ~
                                                                                                    panel, scales = 'free_y')

ggsave(
  filename = "SupF3B.svg",
  plot = temp2,
  width = 13,
  height = 10 * 1.681
)
```

```{r figure3c}

files = list.files(
  path = paste0(root_directory, "/lipids_processed_peakbins"),
  pattern = "peaksum.RData"
)

peak <- list()
for (i in 1:4) {
  load(paste0(
    paste0(root_directory, "/lipids_processed_peakbins"),
    "/",
    files[i]
  ))
  peak[[i]] = peaksum_df
}

##################################### - wassertein distance - take long time to run
within = matrix(0, nrow = 4, ncol = 4)
for (i in 1:4) {
  # if(i == 8){
  #   bw = 1
  #   a = getmzdensity(peak = peak[[i]],n=4096, bandwidth = bw)
  # }else{
  #   a = getmzdensity(peak = peak[[i]],n=4096, bandwidth = "ucv")
  # }
  a = getmzdensity(
    peak = peak[[i]],
    n = 512,
    bandwidth = "nrd0",
    adjust = 1
  )
  for (j in i:4) {
    # if(j == 8){
    #   bw = 5
    #   b = getmzdensity(peak = peak[[j]],n=512, bandwidth =bw)
    # }else{
    #   b = getmzdensity(peak = peak[[j]],n=512 , bandwidth = NULL)
    # }
    b = getmzdensity(
      peak = peak[[j]],
      n = 512 ,
      bandwidth = "nrd0",
      adjust = 1
    )
    within[i, j] = wasserstein(a, b, prob = T)
  }
}
within[lower.tri(within)] = t(within)[lower.tri(within)]
x1 = rep(c(    "9AA-",
    "9AA+",
    "CHCA(2step)-",
    "CHCA(2step)+")
         , times = 4)
x2 = rep(c(    "9AA-",
    "9AA+",
    "CHCA(2step)-",
    "CHCA(2step)+")
         , each = 4)
#within = wasserstein_d_matrix
diag(within) = NA
value = as.vector(within)

matrix_distance = data.frame(cbind(x1, x2, as.double(value)))
######### ggplot

temp = ggplot(matrix_distance, aes(x1, x2)) +
  geom_tile(aes(fill = value)) +
  scale_fill_gradient(
    low = "yellow",
    high = "#00008B",
    na.value = "grey50",
    name = "wasserstein distance"
  ) +
  ggtitle(
    "The heatmap of comparing the mean peaks' intensity across FOV (both tumour/normal) \n,
Computed by kernal density estimation with ucv bandwidth"
  ) + theme_bw() + theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  )


ggsave(
  filename = "wasserstein_distance_lipids2.svg",
  plot = temp,
  width = 11,
  height = 9
)
```


```{r figure3d}
# Set root directory

setwd(paste0(root_directory,"/lipids_processed_peakbins"))
###################
data = readRDS("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230303_lipids/Sarah_Best_Imaging_Lipids_MA-SB-436/output/potential_list_long_2023-03-15.RDS")
matrix_polarity = paste0(data$matrix_short,data$polarity)
#
if(length(grep(colnames(data), pattern = "matrix_polarity")) == 0){
  data = cbind(data, matrix_polarity)
}
####### query database
query <- "select * from analytehaspathway"
con <- connectToRaMP()
allids <- RMariaDB::dbGetQuery(con, query)
RMariaDB::dbDisconnect(con)
kegg_met_allids = subset(allids, pathwaySource == "kegg" & grepl(rampId, pattern ="RAMP_C"))

kegg_identifier = read.csv("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/human/Kegg_pathway_identifier/kegg_classifier.csv")
######################
for(i in 1:4){
  data_r= data[data$matrix_polarity == unique(matrix_polarity)[i],]
  data_r= data_r[!duplicated(data_r$accession),]
  # only operate once
  data_r$accession = paste("hmdb:",data_r$accession,sep="")
  data_r$cas_registry_number = paste("CAS:",data_r$cas_registry_number,sep="")
  data_r$chebi_id = paste("chebi:",data_r$chebi_id,sep="")
  data_r$chemspider_id = paste("chemspider:",data_r$chemspider_idxx,sep="")
  # Create a sample
  pmatrixname = unique(data_r$matrix)
  search= unique(rbind(data.frame(analytes = data_r$accession),
                       data.frame(analytes =subset(data_r$cas_registry_number,nchar(data_r$cas_registry_number)>=5)),
                       data.frame(analytes =subset(data_r$chebi_id,nchar(data_r$chebi_id)>=7)),
                       data.frame(analytes =subset(data_r$chemspider_id,nchar(data_r$hemspider_id)>=12))))
  fisher.results <- RaMP:::runCombinedFisherTest(search, NameOrIds = "ids", total_genes = 20000, 
                                                 MCall = F, alternative = "less", min_path_size = 0, 
                                                 max_path_size = 150000, background_type = "database", 
                                                 background = "database", pathway_definitions = "RaMP")
  #filtered.fisher.results <- FilterFishersResults(fisher.results, pval_type = 'fdr', pval_cutoff=0.05)
  filtered.fisher.results = fisher.results[[1]][which(fisher.results[[1]]$pathwaySource == "kegg"),] %>%
    mutate(id_short = sub("map","",pathwayId) ) %>%
    mutate(  `kegg classifier` = unlist(lapply(id_short, function(x){
      temp = kegg_identifier[which(grepl(pattern = x, kegg_identifier$id)),]$group
      if(length(temp)!=0){
        return(temp) 
      }else{
        temp = "Deleted pathways from Kegg"
      }
    }
    )))%>%
    relocate(`kegg classifier`)
  
  # recalculate the significance
  
  # clusters <- RaMP::findCluster(filtered.fisher.results,
  #                               perc_analyte_overlap = 0.3,
  #                               min_pathway_tocluster = 2, perc_pathway_overlap = 0.2
  # )
  #results = clusters$fishresults %>% mutate_if(is.numeric, ~ round(., 8))
  results = filtered.fisher.results %>% mutate_if(is.numeric, ~ round(., 8))
  ########### append our detected metabolites
  pathwaydf <- getPathwayFromAnalyte(search, includeRaMPids = TRUE, 
                                     NameOrIds = "ids", find_synonym = FALSE)
  filtered_df = pathwaydf[which(pathwaydf$pathwayId %in%  results$pathwayId), ]
  
  # Recalculated p-val
  
  pval =c()
  for(j in 1:nrow(results)){
    total_in_pathway = results$Total_In_Path[j]
    in_data_in_pathway = results$Num_In_Path[j]
    not_in_data_in_pathway = total_in_pathway -  in_data_in_pathway
    in_data_outside_pathway = length(unique(filtered_df$rampId)) -  in_data_in_pathway
    outside_both= length(which(grepl(pattern = "RAMP_C",unique(allids[which(allids$pathwayRampId %in% unique(filtered_df$pathwayRampId)),]$rampId)))) - total_in_pathway - in_data_outside_pathway
    conti_table = data.frame(
      "in_pathway" = c(in_data_in_pathway,not_in_data_in_pathway ),
      "not_in_pathway" = c(in_data_outside_pathway, outside_both ),
      row.names = c("Detected metabolites", "Not detected metabolites"),
      stringsAsFactors = FALSE
    )
    fisher = fisher.test(conti_table, alternative = "greater")
    pval[j] = fisher$p.value
  }
  
  results_final = results %>% 
    mutate(Pval = pval) %>% 
    mutate(Pval_FDR = p.adjust(pval, method = "fdr"))%>% 
    mutate(Pval_Holm = p.adjust(pval, method = "holm")) %>%
    mutate(`Detected versus pathway total ratio` =Num_In_Path/Total_In_Path )%>%
    dplyr::select(-c("id_short","analytes","pathwaySource"))%>%
    rename("kegg_pathwayname"="pathwayName" )%>%
    relocate(`Detected versus pathway total ratio`)%>%
    relocate(`kegg classifier`) %>%
    arrange(Pval)
  
  #########################
  
  name = c()
  for(j in results_final$pathwayId){
    commonname = sub("*;.*","",unique(filtered_df[which(filtered_df$pathwayId==j),]$commonName))
    name = c(name,paste(commonname, collapse = ";\n"))
  }
  results_f = cbind(results_final, Detected_metabolites = name)
  write.csv(results_f, file= paste0( unique(matrix_polarity)[i],"_ORA_enrichment_results_kegg_version.csv"))
  results_f_s = results_f %>% dplyr::select(-Detected_metabolites)
  setwd(paste0(root_directory, "/ORA_lipid_results"))
  write.csv(results_f_s, file= paste0( unique(matrix_polarity)[i],"_ORA_enrichment_results_kegg_no_metabolites_name_version.csv"))
}

############################################################################################## plot
temp = list.files(pattern = "*name_version.csv",
                  path = paste0(root_directory, "/ORA_lipid_results"))
setwd(paste0(root_directory, "/ORA_lipid_results"))
myfiles = lapply(temp, read.csv)
myfiles = lapply(myfiles, function(x) {
  x = x[, 1:10]
  return(x)
})


# Make a data.frame to store graphing stuff
matrixId = c(
    "9AA-",
    "9AA+",
    "CHCA(2step)-",
    "CHCA(2step)+"
)
plotdf = data.frame()
for (i in 1:length(myfiles)) {
  tempdf = cbind(
    "Pathways" = myfiles[[i]]$kegg_pathwayname,
    "Matrix" = rep(matrixId[i], length(myfiles[[i]]$kegg_pathwayname)),
    "pval" = myfiles[[i]]$Pval,
    "fdr_pval" = myfiles[[i]]$Pval_FDR,
    "holm_pval" = myfiles[[i]]$Pval_Holm,
    "id" = myfiles[[i]]$pathwayId,
    "Classifier" = myfiles[[i]]$kegg.classifier,
    "ratio" = myfiles[[i]]$Detected.versus.pathway.total.ratio
  )
  plotdf = rbind(plotdf, tempdf)
}
################################################################################
View(plotdf)
plotdf[which(plotdf$Pathways == "Androgen and Estrogen Metabolism"), ]$Classifier = "5.2 Endocrine system"
plotdf[which(plotdf$Pathways == "Steroidogenesis"), ]$Classifier = "5.2 Endocrine system"
plotdf[which(plotdf$Pathways == "Ketone Body Metabolism"), ]$Classifier = "1.3 Lipid metabolism"
#
#plotdf = plotdf[-which(plotdf$Classifier == "Deleted pathways from Kegg"),]



############
# ggplot(data=plotdf, aes(Matrix, Pathways,colour = FDR_pval)) + geom_point()
# dev.off()
# library(ggplot2)
#
# plotdf$Cluster = sapply(plotdf$Pathways,function(x){
#                  temp = clusters[["fishresults"]][["cluster_assignment"]][which(clusters[["fishresults"]][["pathwayName"]]%in%x)]
#                  return(temp)
#                  })
## Small molecule tissue 2
# pathway_df =  plotdf
# pathway_df[which(pathway_df$Cluster == "6, 11"),]$Cluster = 6
# pathway_df[which(pathway_df$Cluster == "6, 12"),]$Cluster = 6
# pathway_df[which(pathway_df$Cluster == "5, 6"),]$Cluster = 5
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "Glycogen",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "Glu",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "cori",ignore.case = T)),]$Cluster = 2
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "nucleotide",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "purine",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "Methionine",ignore.case = T)),]$Cluster = 3
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "slc",ignore.case = T)),]$Cluster = 1
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "fatty acid",ignore.case = T)
#                  | grepl(pathway_df$Pathway,pattern = "cholestoeol",ignore.case = T)),]$Cluster = 4
# pathway_df[which(grepl(pathway_df$Pathway,pattern = "amino acid",ignore.case = T)),]$Cluster = 5
#
# plotdf =pathway_df
# ####################### Setting colours
cols <- c(
  "Carbohydrate metabolism" = '#0f7321',
  "Energy metabolism" = '#f23a34',
  "Lipid metabolism" = '#008080',
  "Nucleotide metabolism" = '#0069b4',
  "Amino acid metabolism" = '#00ffff',
  "Metabolism of other amino acids" = '#ffa731',
  "Metabolism of cofactors and vitamins" = '#fa2b73',
  "Biosynthesis of other secondary metabolites" = '#f072d4',
  "Endocrine system" = "#0fd214"
)
plotdf = plotdf %>% mutate(group = sub(" ", "", sub(
  ".*[0-9]", "", sub(".*.[1-9]", "", plotdf$Classifier)
))) %>%
  mutate(
    significance = ifelse(
      as.numeric(pval) <= 0.1,
      "Significant at 10% significance level",
      "Not statistically significant"
    )
  )
cols = unlist(cols)
cols <- data.frame(color = unlist(cols),
                   group = names(unlist(cols)))

plotdf <- merge(plotdf, cols, by = "group", all.x = TRUE)
plotdf$Pathways_colour <-
  paste0("<span style=\"color: ",
         plotdf$color,
         "\">",
         plotdf$Pathways,
         "</span>")

plotdf = plotdf[!duplicated(plotdf[, 2:3]), ]

# Get most significant pathways
n = 50
filtered_df = data.frame()
for (i in 1:length(unique(plotdf$Matrix))) {
  temp = plotdf[which(plotdf$Matrix == unique(plotdf$Matrix)[i]), ]
  if (nrow(temp) >= n) {
    temp = temp[order(temp$pval, decreasing = FALSE), ][1:10, ]
  } else{
    temp = temp[order(temp$pval, decreasing = FALSE), ][1:nrow(temp), ]
  }
  if (i == 1) {
    filtered_df = temp
  } else{
    filtered_df = rbind(filtered_df, temp)
  }
}
##############################

temp = ggplot(data = na.omit(plotdf), aes(
  x = factor(
    Matrix,
    level = c(
    "9AA-",
    "9AA+",
    "CHCA(2step)-",
    "CHCA(2step)+"
    )
  ),
  y = Pathways_colour,
  fill = group
)) +
  geom_point(aes(colour = as.numeric(pval), size = as.numeric(ratio))) +
  scale_colour_distiller(
    name = "P value"
    ,
    palette = 'BuGn',
    limits = c(0, 1),
    breaks = seq(0, 1, 0.2),
    direction = -1
  ) +
  scale_size_continuous(name = "Ratio of detected metabolites") +
  new_scale_colour() +
  geom_point(shape = 1, aes(colour = significance, size = as.numeric(ratio))) +
  scale_color_manual(
    values = c(
      "Significant at 10% significance level" = "red",
      "Not statistically significant" = "black"
    )
  ) +
  labs(title = "Comparason of pathways between different matrices",
       y = "Pathways", x = "Matrices molecule/polarity") +
  theme(
    title = element_text(size = 15, face = 'bold'),
    axis.text.x = element_text(
      size = 12,
      angle = 90,
      vjust = 0.5,
      hjust = 1,
      colour = c(
      "9AA-" = "#007AB6",
      "9AA+" = "#ABC7E6",
      "CHCA(2step)+" = "#5AC096",
      "CHCA(2step)-" = "#2FA143"
      )
    ),
    #20
    axis.title = element_text(size = 9),
    #40
    axis.text.y = element_markdown(size = 9),
    legend.key.size = unit(1, 'cm'),
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 9)
  ) +
  new_scale_colour() + theme(panel.background = element_rect(fill = "white"),
                             panel.grid = element_line(color = "grey")) +
  geom_tile(
    aes(fill = group),
    colour = "white",
    width = 0 ,
    height = 0
  ) +
  scale_fill_manual(
    values  = c(
      "Carbohydrate metabolism" = '#0f7321',
      "Energy metabolism" = '#f23a34',
      "Lipid metabolism" = '#008080',
      "Nucleotide metabolism" = '#0069b4',
      "Amino acid metabolism" = '#00ffff',
      "Metabolism of other amino acids" = '#ffa731',
      "Metabolism of cofactors and vitamins" = '#fa2b73',
      "Biosynthesis of other secondary metabolites" = '#f072d4',
      "Endocrine system" = "#0fd214"
    ),
    drop = F,
    name = 'the kegg classifier'
  )

# save image

ggsave(
  filename = "Figure2D_modified.svg",
  plot = temp,
  width = 10,
  height = 14
)
```