---
title: "RMD_pathway_LCMS"
output: html_document
date: "2023-07-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir="/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230516_bulk_metabolomics/programs/")
getwd()
```


```{r readLCMfile}
.libPaths("/stornext/Bioinf/data/lab_brain_cancer/users/t_lu/R/x86_64-pc-linux-gnu-library/4.2")
library(readxl)
library(RRHO2)
library(dplyr)
library(RaMP)
library(ggplot2)
library(magick)
library(rsvg)
library(dplyr)

pkg.globals <- setConnectionToRaMP(
  dbname = "ramp", username = "root", conpass = "ADMIN",
  host = "localhost",socket = "/stornext/Home/data/allstaff/l/lu.t/mysql/var/run/mysqld/mysql.sock")
#########
source_directory = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230516_bulk_metabolomics"
lipid = "/Lipids_LCMS"
polar = "/Polar_LCMS"
# Set working directory
setwd(source_directory)
# Get file names
lipidomics = data.frame(t(read_xlsx(path = paste0(source_directory,lipid,"/",
                                     list.files(paste0(source_directory,lipid),
                                                pattern = "xlsx"))))) 
lipidomics =lipidomics%>% `colnames<-`(paste0(lipidomics[1,],lipidomics[2,]))%>% dplyr::slice(-c(1,2))
#######

polar_molecule = data.frame(t(read_xlsx(path = paste0(source_directory,polar,"/",
                                   list.files(paste0(source_directory,polar),
                                              pattern = "xlsx"))[2]))) 
polar_molecule = polar_molecule%>% dplyr::select(-c(X3,X10)) %>%`colnames<-`(polar_molecule[1,-c(3,10)])%>% dplyr::slice(-c(1))
#####
lcmsdata = list(lipid = lipidomics,
                sm =polar_molecule)
#
```


```{r readIMSfile}
ims_sm_i = readRDS("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/221222_optimization/data/output/potential_list_long_2023-02-10.RDS")
ims_lipid = readRDS("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230303_lipids/Sarah_Best_Imaging_Lipids_MA-SB-436/output/potential_list_long_2023-03-15.RDS")
```


```{r findoverlap_sm}
head(ims_lipid$name)
which(grepl(pattern = "hexosyl", ims_lipid$name))

lcms_sm_hmdb = sub(".*_", "", rownames(lcmsdata[["sm"]]))
lcms_sm = polar_molecule %>% `rownames<-`(lcms_sm_hmdb)
lcms_sm[which(row.names(lcms_sm) == "HMDB0000043"), 1] = 3710 + 7350
####################################################################
matrix_polarity = paste0(ims_sm_i$matrix_short, ims_sm_i$polarity)
#
if (length(grep(colnames(ims_sm_i), pattern = "matrix_polarity")) == 0) {
  ims_sm_i = cbind(ims_sm_i, matrix_polarity)
}
ims_sm = ims_sm_i#[which(ims_sm_i$Tissue == "Tissue1"),]

### Create a df to store the information of the overlapped metabolites
comparason_table = data.frame()
image = list()
all_matched = list()
###########
setwd(
  "/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/small_molecules/Comparason_with_lcms"
)
for (i in unique(matrix_polarity)) {
  ims_temp = ims_sm[which(ims_sm$matrix_polarity == i),]
  ims_matched = ims_temp[which(ims_temp$accession %in% lcms_sm_hmdb),]
  
  ############################
  temp_acession =  ims_matched$accession
  ############################
  ims_matched = ims_matched[!duplicated(ims_matched$accession),]
  ims_rrho = data.frame(cbind(HMDB = ims_matched$accession, diff_ims = ims_matched$diff_mean))
  # Lcms data
  lcms_temp = lcms_sm[which(rownames(lcms_sm) %in% unique(ims_temp$accession)),]
  #remove background
  lcms_fc = log1p(as.numeric(lcms_temp[, 2]) - as.numeric(lcms_temp[, ncol(lcms_temp)])) - log1p(as.numeric(lcms_temp[, 1]) -
                                                                                                   as.numeric(lcms_temp[, ncol(lcms_temp)]))
  lcms_rrho = data.frame(cbind(HMDB = rownames(lcms_temp), diff_lcms =  lcms_fc))
  
  all_matched[[i]] = merge(ims_rrho, lcms_rrho, by = c("HMDB"))
  # mean_dm = log1p(mean(exp(ims_temp[which(ims_temp$accession==temp_acession),]$mean_c)-1)/mean(exp(ims_temp[which(ims_temp$accession==temp_acession),]$mean_h)-1))
  for (j in temp_acession) {
    temp = ims_temp[which(ims_temp$accession == j),]
    mean_dm =  temp[which.min(abs(as.numeric(temp$diff_mean) - as.numeric(lcms_rrho[which(lcms_rrho[, 1] == j), 2]))),]$diff_mean
    ##############
    ims_matched[which(ims_matched$accession == j),]$diff_mean = mean_dm
  }
  
  test = data.frame(
    ac = cbind(
      ims_matched$accession,
      dm = ims_matched$diff_mean,
      hmdb = ims_matched$mz_hmdb,
      detected_mz = ims_matched$exp_mz
    )
  )
  #### fiNAL MUTUAL MATCH
  ims_rrho = ims_rrho[which(ims_rrho[, 1] %in% lcms_rrho[, 1]),]
  
  # plot
  if (nrow(ims_rrho) <= 10) {
    RRHO_obj <-
      RRHO2_initialize(
        ims_rrho,
        lcms_rrho,
        stepsize = 5,
        labels = c("ims", "lcms"),
        log10.ind = F,
        method = "hyper"
      )
  } else{
    RRHO_obj <-
      RRHO2_initialize(
        ims_rrho,
        lcms_rrho,
        stepsize = 3,
        labels = c("ims", "lcms"),
        log10.ind = F,
        method = "hyper"
      )
  }
  
  svglite::svglite(paste0(i, ".svg"), width = 6, height = 4)
  RRHO2_heatmap(
    x = seq(
      min(ims_rrho[, 2]),
      max(ims_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    y = seq(
      min(lcms_rrho[, 2]),
      max(lcms_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    RRHO_obj,
    main = i
  )
  
  RRHO2_heatmap(
    x = seq(
      min(ims_rrho[, 2]),
      max(ims_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    y = seq(
      min(lcms_rrho[, 2]),
      max(lcms_rrho[, 2]),
      length.out = nrow(RRHO_obj$hypermat)
    ),
    RRHO_obj,
    main = i
  )
  dev.off()
  ########### get analytic table
  uu = getPathwayFromAnalyte(paste0("HMDB:", RRHO_obj$genelist_uu$gene_list_overlap_uu))
  uu = uu[!duplicated(uu$pathwayName),]
  uu_comparason_table = data.frame(
    HMDB = RRHO_obj$genelist_uu$gene_list_overlap_uu,
    `logFC(Cancer versus normal) IMS` = ims_rrho[which(ims_rrho[, 1] %in% RRHO_obj$genelist_uu$gene_list_overlap_uu), 2],
    `logFC(Cancer versus normal) LCMS` = lcms_rrho[which(lcms_rrho[, 1] %in% RRHO_obj$genelist_uu$gene_list_overlap_uu), 2],
    `Metabolite name` = unlist(
      lapply(RRHO_obj$genelist_uu$gene_list_overlap_uu, function(x) {
        temp = uu[which(grepl(pattern = x,
                              uu$inputId)),]$commonName[1]
        return(temp)
      })
    ),
    `Common trend` = rep(
      "Both upregulated in tumour",
      times = length(RRHO_obj$genelist_uu$gene_list_overlap_uu)
    ),
    `Detected matrix` = rep(i, times = length(
      RRHO_obj$genelist_uu$gene_list_overlap_uu
    ))
  )
  ## downdown
  dd = getPathwayFromAnalyte(paste0("HMDB:", RRHO_obj$genelist_dd$gene_list_overlap_dd))
  dd = dd[!duplicated(dd$pathwayName),]
  dd_comparason_table = data.frame(
    HMDB = RRHO_obj$genelist_dd$gene_list_overlap_dd,
    `logFC(Cancer versus normal) IMS` = ims_rrho[which(ims_rrho[, 1] %in% RRHO_obj$genelist_dd$gene_list_overlap_dd), 2],
    `logFC(Cancer versus normal) LCMS` = lcms_rrho[which(lcms_rrho[, 1] %in% RRHO_obj$genelist_dd$gene_list_overlap_dd), 2],
    `Metabolite name` = unlist(
      lapply(RRHO_obj$genelist_dd$gene_list_overlap_dd, function(x) {
        temp = dd[which(grepl(pattern = x,
                              dd$inputId)),]$commonName[1]
        return(temp)
      })
    ),
    `Common trend` = rep(
      "Both downregulated in tumour",
      times = length(RRHO_obj$genelist_dd$gene_list_overlap_dd)
    ),
    `Detected matrix` = rep(i, times = length(
      RRHO_obj$genelist_dd$gene_list_overlap_dd
    ))
  )
  temp_comparason_table = rbind(uu_comparason_table,
                                dd_comparason_table)
  comparason_table = rbind(comparason_table,
                           temp_comparason_table)
}

for (i in 1:nrow(comparason_table)) {
  if (is.na(comparason_table[i,]$Metabolite.name)) {
    comparason_table[i,]$Metabolite.name = unique(ims_sm[which(ims_sm$accession == comparason_table[i,]$HMDB),]$name)[1]
  }
}
write.csv(comparason_table,
          file = "Common_up_down_regulated_small_molecule_metabolites_in_ims.csv")


for (i in unique(matrix_polarity)) {
  image[[i]] = image_read_svg(paste0(i, ".svg")) |> image_ggplot()
}
svglite::svglite(paste0("all.svg"), width = 10, height = 15)
gridExtra::grid.arrange(image[[1]],
                        image[[2]],
                        image[[3]],
                        image[[4]],
                        image[[5]],
                        image[[6]],
                        image[[7]],
                        image[[8]],
                        image[[9]],
                        image[[10]],
                        ncol = 2)
dev.off()

save(RRHO2_heatmap, file = "RRHO_heatmap.Rdata")
```

```{r ratio}
matched_hmdb = all_matched

ratio_df = data.frame()
for (i in 1:length(all_matched)) {
num_matched_hmdb = nrow(all_matched[[i]])
num_matched_same_direction_hmdb = length(which(comparason_table$Detected.matrix == names(all_matched)[i]))
ratio_df = rbind(
ratio_df,
rbind(
data.frame(
num_matched_hmdb = num_matched_hmdb - num_matched_same_direction_hmdb,
num_matched_lcms = 145,
matrix = names(all_matched)[i],
marker = "All matched metabolites"
)
),
data.frame(
num_matched_hmdb = num_matched_same_direction_hmdb,
num_matched_lcms = 145,
matrix = names(all_matched)[i],
marker = "Matched metabolites of same direction"
)
)
}
library(ggplot2)
library(viridis)
library(ggpattern)
#

#
temp = ggplot(
ratio_df,
aes(
fill = matrix,
y = num_matched_hmdb/num_matched_lcms*100,
x = factor(matrix, level = c("9AA -",
"9AA +" ,
"9AA (2step)-" ,
"9AA (2step)+",
"DHB -" ,
 "DHB +" ,
"CHCA  (2step)-",
"CHCA  (2step)+" ,
"CHCA -",
 "CHCA +" )),
pattern = marker
)
) +
geom_bar(position = "stack", stat = "identity") +
geom_bar_pattern(
position = "stack",
stat = "identity",
color = "black",
pattern_fill = "black",
pattern_angle = 45,
pattern_density = 0.1,
pattern_spacing = 0.025,
pattern_key_scale_factor = 0.6
) +
scale_pattern_manual(
values = c(
`Matched metabolites of same direction` = "stripe",
`All matched metabolites` = "none"
)
) +
scale_fill_manual(values = rep(
c(
"9AA -" = "#007AB6",
"9AA +" = "#ABC7E6",
"9AA (2step)-" = "#413975",
"9AA (2step)+"= "#9068AC",
"DHB +" = "#FDB772",
 "DHB -" ="#F77800",
"CHCA  (2step)+" = "#5AC096",
"CHCA  (2step)-" = "#2FA143",
"CHCA +" = "#C3A128",
 "CHCA -" = "#916729"
),
each = 1
), guide = "none") +
labs(x = "Matrix/Polarity combinations", y = "Percentage of overlapping metabolites with LCMS (%)", pattern = "Whether the overlapping metabolites \n detected in IMS has same regulatory direction \n as the one detected in LCMS") +
ggtitle("Ratio of overlapping metabolites with LCMS for each IMS matrices") + theme(panel.background = element_rect(fill = "white"),
panel.grid = element_line(color = "grey")) +scale_x_discrete(guide=guide_axis(n.dodge=2))

setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(
filename = "Figure2B.svg",
plot = temp,
width = 13,
height = 6 * 1.618,
dpi = 600
)
```
