---
title: "meta_of_interest"
output: html_document
date: "2023-07-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(RaMP)
files = list.files(path = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output",
                   pattern = "RDS")
data =list()
for(i in 1:4){
  data[[i]] = readRDS(paste0("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/230509_human_optimization/data/output/",
                            files[i]))
}
data = readRDS("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/221222_optimization/data/output/potential_list_long_2023-02-10.RDS")
matrix_polarity = paste0(data$matrix, data$polarity)
#
if(length(grep(colnames(data), pattern = "matrix_polarity")) == 0){
  data = cbind(data, matrix_polarity)
}
```

```{r list_moi}
moi_list = c("D-Glucose",
             "Glucose-6-glutamate",
             "L-Glutamine",
             "D-Glutamine",
             "L-Glutamic acid",
             "DL-Glutamate",
             "D-threo-isocitrate",
             "Taurine",
             "Ascorbic acid",
             "Glutathione",
             "Linoleic acid",
             "N-Acetyl-L-aspartic acid",
             "Inosine",
             "Uridine 5'-monophosphate",
             "Uridine"
             )
# names = unique(data[which(grepl(data$chemical_formula, pattern = "C9H14N2O12P2",ignore.case = T)),]$name)
# 
# names = unique(data[which(grepl(data$name, pattern = "uridine",ignore.case = T)),]$name)
# test = lapply(names, function(x){
#  temp = unique(data[which(data$name == x),]$matrix_polarity)
#  return(temp)
#    }
#  )
# names(test)=names
heatmap_df = data.frame()
for(i in unique(matrix_polarity)){
  #i = unique(matrix_polarity)[3]
  df = data[which(data$matrix_polarity == i),]
  temp = data.frame(unlist(lapply(moi_list, function(x){
    temp = mean(df[which(df$name==x),]$diff_mean)
    return(temp)
  }
  )
  ))
 temp = cbind(temp,moi_list,rep(i,times = length(moi_list)))
 colnames(temp) = c("diff_mean",
                    "Metabolites' list",
                    "Matrix")
 if(i == unique(matrix_polarity)[1]){
   heatmap_df= temp
 }else{
   heatmap_df = rbind(heatmap_df,temp)
 }
}


#plot
temp = ggplot(heatmap_df,aes(x=Matrix,
                      y=`Metabolites' list`,
                      fill = diff_mean)) +
  geom_tile(color = "black") +
  scale_fill_gradient2(low = "#075AFF",
                       high = "#FF0000") +
  coord_fixed()+
  theme(axis.text.x = element_text(angle = 90))

setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(filename = "SupF2B_reverse.svg",
       plot = temp,
       width=6, height=6*1.681)


```
