---
title: "RMD_pathway"
output: html_document
date: "2023-07-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir="/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/human/Kegg_pathways_csv")
getwd()
```


```{r env}
# overlaped pathways between each matrix
.libPaths("/stornext/Bioinf/data/lab_brain_cancer/users/t_lu/R/x86_64-pc-linux-gnu-library/4.2")
library(ggplot2)
library(MASS) 
library(reshape2)
library(RaMP)
library(ggplot2movies)
library(data.table)
library(ComplexUpset)
library(ggtext)
pkg.globals <- setConnectionToRaMP(
  dbname = "ramp", username = "root", conpass = "ADMIN",
  host = "localhost",socket = "/stornext/Home/data/allstaff/l/lu.t/mysql/var/run/mysqld/mysql.sock")
```

```{r readfiles}
# Read files
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/human/Kegg_pathways_csv")
temp = list.files(pattern="*name_version.csv",
                  recursive = T)
myfiles = lapply(temp, read.csv)
myfiles = lapply(myfiles, function(x){
  x = x[,1:10]
  return(x)
}
)
temp
```
```{r humansample}
# Make sure the order as the temp file listed
matrixId = c("9AA-(Lipid)",
             "9AA-(Small_molecule)",
             "CHCA-(Recrystallisation_lipid)",
             "CHCA-(Recrystallisation_small_molecule)"
)

plotdf = data.frame()
for(i in 1:length(myfiles)){
  temp = myfiles[[i]][which(myfiles[[i]]$Detected.versus.pathway.total.ratio >= 0.4),]
  tempdf = cbind(temp$kegg_pathwayname,
                 rep(matrixId[i],length(temp$kegg_pathwayname)),
                 temp$Pval,
                 temp$kegg.classifier,
                 temp$Detected.versus.pathway.total.ratio)
  plotdf = rbind(plotdf,tempdf)
}
# find clusters

colnames(plotdf) = c("Pathways",
                     "Matrix",
                     "Pval",
                     "Cluster",
                     "Ratio")
plotdf$Pval = as.double(plotdf$Pval)
plotdf = plotdf[which(!duplicated(plotdf[,1:2])),]


################## get the matrix for upsetplot
pathway_df = data.frame(matrix(0, ncol=length(matrixId)+4, nrow = length(unique(plotdf$Pathways))))
colnames(pathway_df)= c(matrixId,"Cluster","Pathway_names")
for(i in 1: length(unique(plotdf$Pathways))){
  match = plotdf[which(plotdf$Pathways == unique(plotdf$Pathways)[i]),]$Matrix
  pathway_df[i,which(colnames(pathway_df) %in% match)] = 1
  pathway_df[i,length(matrixId)+1] = plotdf[which(plotdf$Pathways == unique(plotdf$Pathways)[i]),]$Cluster[1]
  pathway_df[i,length(matrixId)+2] = unique(plotdf$Pathways)[i]
  pathway_df[i,length(matrixId)+3] = unique(plotdf$Pval)[i]
  pathway_df[i,length(matrixId)+4] = unique(plotdf$Ratio)[i]
}
######################################
cluster_name = c("Carbohydrate metabolism",
                 "Energy metabolism",
                 "Lipid metabolism",
                 "Nucleotide metabolism",
                 "Amino acid metabolism",
                 "Metabolism of other amino acids",
                 "Metabolism of cofactors and vitamins",
                 "Biosynthesis of other secondary metabolites"
                 )
index = naturalsort::naturalsort(unique(pathway_df$Cluster))
cluster_assign = c()
for(i in 1:length(cluster_name)){
  cluster_assign[which(pathway_df$Cluster == index[i])] =cluster_name[i]
}
pathway_df1 = cbind(pathway_df,"Kegg classifier of pathways" = cluster_assign)
colnames(pathway_df1)[7] = "pval"
colnames(pathway_df1)[8] = "ratio"

upset = upset(
  pathway_df1,
  matrixId,
  base_annotations=list(
    'Intersection size'=intersection_size(
      counts=FALSE,
      mapping=aes(fill=`Kegg classifier of pathways`)) + scale_fill_manual(values=c(
                 "Carbohydrate metabolism"= '#0f7321',
                 "Energy metabolism"='#f23a34',
                 "Lipid metabolism"='#008080',
                 "Nucleotide metabolism"='#0069b4',
                 "Amino acid metabolism"='#00ffff',
                 "Metabolism of other amino acids"='#ffa731',
                 "Metabolism of cofactors and vitamins"='#fa2b73',
                 "Biosynthesis of other secondary metabolites"= '#f072d4'
    ))+
      ggtitle('Pathway analysis on metabolic profile generated for each matrix/polarity combination')
  ),
  group_by='degree',
  matrix=(
    intersection_matrix(geom=geom_point(shape='circle filled', size=2))
    + scale_color_manual(
      values=c("9AA-(Lipid)"="#007AB6",
             "9AA-(Small_molecule)"="#ABC7E6",
             "CHCA-(Recrystallisation_lipid)"="#5AC096",
             "CHCA-(Recrystallisation_small_molecule)"="#2FA143"),
      guide=guide_legend(override.aes=list(shape='circle'))
    )
  ),
  queries=list(
    upset_query(set="9AA-(Lipid)", fill='#007AB6'),
    upset_query(set="9AA-(Small_molecule)", fill='#ABC7E6'),
    upset_query(set='CHCA-(Recrystallisation_lipid)', fill ='#5AC096'),
    upset_query(set='CHCA-(Recrystallisation_small_molecule)', fill ='#2FA143')
  ),
  width_ratio=0.1
)
####
####
```


```{r saveplot}
ggsave(filename = "pathway_UPSET_human_ratio40.svg",
       plot = upset,
       width=8*1.681, height=6,
       dpi = 300)
```


```{r dotplot}

# Make a data.frame to store graphing stuff
matrixId = c("9AA-(Lipid)",
             "9AA-(Small_molecule)",
             "CHCA-(Recrystallisation_lipid)",
             "CHCA-(Recrystallisation_small_molecule)"
)

plotdf = data.frame()
for(i in 1:length(myfiles)){
  # 40% or more will be selected
  temp = myfiles[[i]][which(myfiles[[i]]$Detected.versus.pathway.total.ratio >= 0.4),]
  tempdf = cbind(temp$kegg_pathwayname,
                 rep(matrixId[i],length(temp$kegg_pathwayname)),
                 temp$Pval,
                 temp$kegg.classifier,
                 temp$Detected.versus.pathway.total.ratio)
  plotdf = rbind(plotdf,tempdf)
}

# find clusters


#set colnames

colnames(plotdf) = c("Pathways",
                     "Matrix",
                     "Pval",
                     "Cluster",
                     "Ratio")
plotdf$Pval = as.double(plotdf$Pval)
plotdf = plotdf[which(!duplicated(plotdf[,1:2])),]
############



# Tissue2 colours
cols <- c("Carbohydrate metabolism"= '#0f7321',
                 "Energy metabolism"='#f23a34',
                 "Lipid metabolism"='#008080',
                 "Nucleotide metabolism"='#0069b4',
                 "Amino acid metabolism"='#00ffff',
                 "Metabolism of other amino acids"='#ffa731',
                 "Metabolism of cofactors and vitamins"='#fa2b73',
                 "Biosynthesis of other secondary metabolites"= '#f072d4'
        )

cols <- data.frame(Cluster =naturalsort::naturalsort(unique(plotdf$Cluster)) , color = cols[1:length(naturalsort::naturalsort(unique(plotdf$Cluster)))])
plotdf <- merge(plotdf, cols, by = "Cluster", all.x = TRUE)
plotdf$Pathways_colour <- paste0("<span style=\"color: ", plotdf$color, "\">", plotdf$Pathways, "</span>")

plotdf = plotdf[!duplicated(plotdf[,2:3]),]

#Select significant pathways
p = 0.1
plotdf = data.frame(plotdf,
                    sig = ifelse(as.numeric(plotdf$Pval)<=p,"Significant","non-significant"),
                    sig_colour = ifelse(as.numeric(plotdf$Pval)<=p,"red","none"))

library(ggnewscale)
temp = ggplot(data=plotdf, aes(x = Matrix, y = Pathways_colour))+ 
       geom_point(aes(colour = as.numeric(Pval),size = as.numeric(Ratio)))+
       scale_size_continuous(name = "ratio of detected metabolites")+
            scale_colour_distiller(name="P value" 
                                     ,palette = 'BuGn',
            limits = c(0, 1), breaks = seq(0,1,0.2),
            direction= -1) +
       new_scale_colour() +
       geom_point(shape = 1,aes(colour= as.factor(sig),
                             size = as.numeric(Ratio)))+
            scale_colour_manual(values = c("non-significant" = 'black',
                                         "Significant" = 'red'),
                                name = "Whether the pathway is significant")+
            #scale_size_manual(name = "ratio of detected metabolites")+
   labs(
         title = "Comparason of pathways between different matrices",
         y = "Pthways", x = "Matrices molecule-polarity-target-molecules")+
       theme(title =element_text(size=15, face='bold'),
         axis.text.x = element_text(size = 12,
                                  angle =45,
                                  vjust = 1, hjust=1,
                                  colour = c("9AA-(Lipid)"="#007AB6",
             "9AA-(Small_molecule)"="#ABC7E6",
             "CHCA-(Recrystallisation_lipid)"="#5AC096",
             "CHCA-(Recrystallisation_small_molecule)"="#2FA143"
                                    )),#20
            axis.title = element_text(size = 20),#40
            axis.text.y = element_markdown(size=9),
            legend.key.size = unit(1, 'cm'),
            legend.title = element_text(size=13),
            legend.text = element_text(size=13))+ theme(panel.background = element_rect(fill = "white"),
                                               panel.grid = element_line(color = "grey"))
# save image
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/human/human_pathway_plots")
ggsave(filename = "Pathway_dot_plot.svg",
       plot = temp,
       width=10, height=8*1.618,dpi =600)
```


```{r sm}
setwd("~/paper/Optimisation/ORA_Enrichment_Tissue1_general_background")
temp = list.files(pattern="*name_version.csv",
                  recursive = T)
myfiles = lapply(temp, read.csv)
myfiles = lapply(myfiles, function(x){
  x = x[,1:10]
  return(x)
}
)
temp
# Make sure the order as the temp file listed
matrixId =  c("9AA-",
             "9AA-(Recrystallisation)",
             "9AA+(Recrystallisation)",
             "9AA+",
             "CHCA-(Recrystallisation)",
             "CHCA+(Recrystallisation)",
             "CHCA-",
             "CHCA+",
             "DHB-",
             "DHB+")

plotdf = data.frame()
for(i in 1:length(myfiles)){
  temp = myfiles[[i]][which(myfiles[[i]]$Detected.versus.pathway.total.ratio >=0.2),]
  tempdf = cbind(temp$kegg_pathwayname,
                 rep(matrixId[i],length(temp$kegg_pathwayname)),
                 temp$Pval,
                 temp$kegg.classifier,
                 temp$Detected.versus.pathway.total.ratio)
  plotdf = rbind(plotdf,tempdf)
}
# find clusters

colnames(plotdf) = c("Pathways",
                     "Matrix",
                     "Pval",
                     "Cluster",
                     "Ratio")
plotdf$Pval = as.double(plotdf$Pval)
plotdf = plotdf[which(!duplicated(plotdf[,1:2])),]


################## get the matrix for upsetplot
pathway_df = data.frame(matrix(0, ncol=length(matrixId)+4, nrow = length(unique(plotdf$Pathways))))
colnames(pathway_df)= c(matrixId,"Cluster","Pathway_names")
for(i in 1: length(unique(plotdf$Pathways))){
  match = plotdf[which(plotdf$Pathways == unique(plotdf$Pathways)[i]),]$Matrix
  pathway_df[i,which(colnames(pathway_df) %in% match)] = 1
  pathway_df[i,length(matrixId)+1] = plotdf[which(plotdf$Pathways == unique(plotdf$Pathways)[i]),]$Cluster[1]
  pathway_df[i,length(matrixId)+2] = unique(plotdf$Pathways)[i]
  pathway_df[i,length(matrixId)+3] = unique(plotdf$Pval)[i]
  pathway_df[i,length(matrixId)+4] = unique(plotdf$Ratio)[i]
}
######################################
cluster_name = c("Carbohydrate metabolism",
                 "Energy metabolism",
                 "Lipid metabolism",
                 "Nucleotide metabolism",
                 "Amino acid metabolism",
                 "Metabolism of other amino acids",
                 "Metabolism of cofactors and vitamins",
                 "Biosynthesis of other secondary metabolites"
                 )
index = naturalsort::naturalsort(unique(pathway_df$Cluster))
cluster_assign = c()
for(i in 1:length(cluster_name)){
  cluster_assign[which(pathway_df$Cluster == index[i])] =cluster_name[i]
}
pathway_df1 = cbind(pathway_df,"Kegg classifier of pathways" = cluster_assign)
colnames(pathway_df1)[7] = "pval"
colnames(pathway_df1)[8] = "ratio"

upset = upset(
  pathway_df1,
  matrixId,
  base_annotations=list(
    'Intersection size'=intersection_size(
      counts=FALSE,
      mapping=aes(fill=`Kegg classifier of pathways`)) + scale_fill_manual(values=c(
                 "Carbohydrate metabolism"= '#0f7321',
                 "Energy metabolism"='#f23a34',
                 "Lipid metabolism"='#008080',
                 "Nucleotide metabolism"='#0069b4',
                 "Amino acid metabolism"='#00ffff',
                 "Metabolism of other amino acids"='#ffa731',
                 "Metabolism of cofactors and vitamins"='#fa2b73',
                 "Biosynthesis of other secondary metabolites"= '#f072d4'
    ))+
      ggtitle('Pathway analysis on metabolic profile generated for each matrix/polarity combination')
  ),
  group_by='degree',
  matrix=(
    intersection_matrix(geom=geom_point(shape='circle filled', size=2))
    + scale_color_manual(
      values=c("9AA-(Lipid)"="#007AB6",
             "9AA-(Small_molecule)"="#ABC7E6",
             "CHCA-(Recrystallisation_lipid)"="#5AC096",
             "CHCA-(Recrystallisation_small_molecule)"="#2FA143"),
      guide=guide_legend(override.aes=list(shape='circle'))
    )
  ),
  queries=list(
    upset_query(set="9AA-(Lipid)", fill='#007AB6'),
    upset_query(set="9AA-(Small_molecule)", fill='#ABC7E6'),
    upset_query(set='CHCA-(Recrystallisation_lipid)', fill ='#5AC096'),
    upset_query(set='CHCA-(Recrystallisation_small_molecule)', fill ='#2FA143')
  ),
  width_ratio=0.1
)
####
####
```


```{r saveplot}
ggsave(filename = "pathway_UPSET_human_ratio40.svg",
       plot = upset,
       width=8*1.681, height=6,
       dpi = 300)
```


```{r dotplotsm}

# Make a data.frame to store graphing stuff
matrixId = c("9AA-(Lipid)",
             "9AA-(Small_molecule)",
             "CHCA-(Recrystallisation_lipid)",
             "CHCA-(Recrystallisation_small_molecule)"
)

plotdf = data.frame()
for(i in 1:length(myfiles)){
  # 40% or more will be selected
  temp = myfiles[[i]][which(myfiles[[i]]$Detected.versus.pathway.total.ratio >= 0.4),]
  tempdf = cbind(temp$kegg_pathwayname,
                 rep(matrixId[i],length(temp$kegg_pathwayname)),
                 temp$Pval,
                 temp$kegg.classifier,
                 temp$Detected.versus.pathway.total.ratio)
  plotdf = rbind(plotdf,tempdf)
}

# find clusters


#set colnames

colnames(plotdf) = c("Pathways",
                     "Matrix",
                     "Pval",
                     "Cluster",
                     "Ratio")
plotdf$Pval = as.double(plotdf$Pval)
plotdf = plotdf[which(!duplicated(plotdf[,1:2])),]
############



# Tissue2 colours
cols <- c("Carbohydrate metabolism"= '#0f7321',
                 "Energy metabolism"='#f23a34',
                 "Lipid metabolism"='#008080',
                 "Nucleotide metabolism"='#0069b4',
                 "Amino acid metabolism"='#00ffff',
                 "Metabolism of other amino acids"='#ffa731',
                 "Metabolism of cofactors and vitamins"='#fa2b73',
                 "Biosynthesis of other secondary metabolites"= '#f072d4'
        )

cols <- data.frame(Cluster =naturalsort::naturalsort(unique(plotdf$Cluster)) , color = cols[1:length(naturalsort::naturalsort(unique(plotdf$Cluster)))])
plotdf <- merge(plotdf, cols, by = "Cluster", all.x = TRUE)
plotdf$Pathways_colour <- paste0("<span style=\"color: ", plotdf$color, "\">", plotdf$Pathways, "</span>")

plotdf = plotdf[!duplicated(plotdf[,2:3]),]

#Select significant pathways
p = 0.1
plotdf = data.frame(plotdf,
                    sig = ifelse(plotdf$Pval<=p,"Significant","non-significant"),
                    sig_colour = ifelse(plotdf$Pval<=p,"red","none"))

library(ggnewscale)
temp = ggplot(data=plotdf, aes(x = Matrix, y = Pathways_colour))+ 
       geom_point(aes(colour = as.numeric(Pval),size = as.numeric(Ratio)))+
       scale_size_continuous(name = "ratio of detected metabolites")+
            scale_colour_distiller(name="P value" 
                                     ,palette = 'BuGn',
            limits = c(0, 1), breaks = seq(0,1,0.2),
            direction= -1) +
       new_scale_colour() +
       geom_point(shape = 1,aes(colour= as.factor(sig),
                             size = as.numeric(Ratio)))+
            scale_colour_manual(values = c("non-significant" = 'black',
                                         "Significant" = 'red'),
                                name = "Whether the pathway is significant")+
            #scale_size_manual(name = "ratio of detected metabolites")+
   labs(
         title = "Comparason of pathways between different matrices",
         y = "Pthways", x = "Matrices molecule-polarity-target-molecules")+
       theme(title =element_text(size=15, face='bold'),
         axis.text.x = element_text(size = 12,
                                  angle =45,
                                  vjust = 1, hjust=1,
                                  colour = c("9AA-(Lipid)"="#007AB6",
             "9AA-(Small_molecule)"="#ABC7E6",
             "CHCA-(Recrystallisation_lipid)"="#5AC096",
             "CHCA-(Recrystallisation_small_molecule)"="#2FA143"
                                    )),#20
            axis.title = element_text(size = 20),#40
            axis.text.y = element_markdown(size=9),
            legend.key.size = unit(1, 'cm'),
            legend.title = element_text(size=13),
            legend.text = element_text(size=13))+ theme(panel.background = element_rect(fill = "white"),
                                               panel.grid = element_line(color = "grey"))
# save image
setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/human/human_pathway_plots")
ggsave(filename = "Pathway_dot_plot.svg",
       plot = temp,
       width=10, height=8*1.618,dpi =600)
```


```{r backgroundpeaks}
src_file = "/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/221222_optimization/data/output"
peaksum = list.files(src_file ,
                    pattern = "Tissue1_T_peaksum.RData")
peaks = naturalsort::naturalsort(peaksum)
num_b_peaks = c()
for(i in 1:length(peaks)){
  load(paste0(src_file,"/",peaks[i]))
  num_b_peaks[i] = nrow(peaksum_b_df)
}

matrixId =  c("9AA Sublimation-",
              "9AA Sublimation+",
             "9AA Sublimation(2step)-",
             "9AA Sublimation(2step)+",
             "DHB Sublimation+",
             "DHB Sublimation-",
             "CHCA sublimation (2step)+",
             "CHCA sublimation (2step)-",
             "CHCA sublimation+",
             "CHCA sublimation-")
num_back1 = cbind(matrix = matrixId,
peaks = num_b_peaks)
                 

#############
data = readRDS("/stornext/Bioinf/data/lab_brain_cancer/projects/tme_spatial/metabolomics/221222_optimization/data/output/potential_list_long_2023-02-10.RDS")

matrix_polarity = paste0(data$matrix, data$polarity)
#
if(length(grep(colnames(data), pattern = "matrix_polarity")) == 0){
  data = cbind(data, matrix_polarity)
}
data[which(data$matrix_polarity == unique(matrix_polarity[1])),]$m
data$mz_hmdb
# num stores the number of unique detected small molecules, num_mz, number of unique m/z s
num = c()
num_mz = c()
#
for(i in 1:length(unique(matrix_polarity))){
  num_mz[i] = length(unique(data[which(data$matrix_polarity == unique(matrix_polarity)[i] & data$Tissue == "Tissue1" ),]$mz_hmdb))
  num[i] = length(unique(data[which(data$matrix_polarity == unique(matrix_polarity)[i]& data$Tissue == "Tissue1"),]$accession  ))
}

num_mz = data.frame(matrix = unique(matrix_polarity),
peaks = num_mz)
###############
num_total = cbind(rbind(num_mz, num_back1),
                 label = rep(c("Unique matched m/z peaks",
                        "Unique background m/z peaks"),each = 10))

library(ggplot2)
library(viridis)
library(ggpattern)
temp = ggplot(
num_total,
aes(
fill = matrix,
y = as.integer(peaks),
x = factor(matrix, level = c(
"9AA Sublimation-",
              "9AA Sublimation+",
             "9AA Sublimation(2step)-",
             "9AA Sublimation(2step)+",
             "DHB Sublimation-",
             "DHB Sublimation+",
             "CHCA sublimation (2step)-",
             "CHCA sublimation (2step)+",
             "CHCA sublimation-",
             "CHCA sublimation+")),
pattern = label
)
) +
geom_bar_pattern(
position = "dodge",
stat = "identity",
color = "black",
pattern_fill = "black",
pattern_angle = 45,
pattern_density = 0.1,
pattern_spacing = 0.025,
pattern_key_scale_factor = 0.6
) +
scale_pattern_manual(
values = c(
`Unique background m/z peaks` = "stripe",
`Unique matched m/z peaks` = "none"
)
) +
scale_fill_manual(values = rep(
c(
"9AA Sublimation-" = "#007AB6",
"9AA Sublimation+" = "#ABC7E6",
"9AA Sublimation(2step)-" = "#413975",
"9AA Sublimation(2step)+"= "#9068AC",
"DHB Sublimation+" = "#FDB772",
"DHB Sublimation-"="#F77800",
"CHCA sublimation (2step)+" = "#5AC096",
"CHCA sublimation (2step)-" = "#2FA143",
"CHCA sublimation+" = "#C3A128",
"CHCA sublimation-" = "#916729"
),
each = 1
), guide = "none") +
labs(x = "Matrix/Polarity combinations", y = "Number of peaks detected", pattern = "Background versus Tissue peaks") +
ggtitle("Ratio of overlapping metabolites with LCMS for each IMS matrices") + theme(panel.background = element_rect(fill = "white"),
panel.grid = element_line(color = "grey")) +scale_x_discrete(guide=guide_axis(n.dodge=2))

setwd("/stornext/Bioinf/data/lab_brain_cancer/manuscripts/2023_metabolomics/plots/Figure2")
ggsave(
filename = "SupF2A.svg",
plot = temp,
width = 13,
height = 6 * 1.618,
dpi = 600
)

ppm = 50
filter = unlist(lapply(a, function(x){
  if(all(b-(50*1e-6)>x | x>b+(50*1e-6))){
    return(x)
  }else{
    return(NA)
  }
})) %>% na.omit()
```